const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
const esc = v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
const svgPaths={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',products:'<path d="m3 7 9-4 9 4v11l-9 4-9-4zM3 7l9 4 9-4M12 11v11M7 5l10 5"/>',services:'<path d="M14 6a5 5 0 0 0-6 6L3 17a3 3 0 0 0 4 4l5-5a5 5 0 0 0 6-6l-3 3-4-4z"/>',website:'<rect x="3" y="4" width="18" height="16"/><path d="M3 9h18M7 6.5h1M10 6.5h1M8 13h8M8 16h5"/>',photos:'<rect x="3" y="3" width="18" height="18"/><path d="m3 17 6-6 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.4"/>',requests:'<path d="M4 3h16v18H4zM8 7h8M8 11h8M8 15h4"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><rect x="7" y="4" width="4" height="4"/><rect x="14" y="10" width="4" height="4"/><rect x="7" y="16" width="4" height="4"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6"/>',price:'<path d="M3 3h8l10 10-8 8L3 11z"/><circle cx="7" cy="7" r="1"/>',plus:'<path d="M12 4v16M4 12h16"/>',edit:'<path d="m4 16 12-12 4 4L8 20H4zM13 7l4 4"/>',check:'<path d="m4 12 5 5L20 6"/>',shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6zM8 12l3 3 5-6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v7M12 6v1"/>',folder:'<path d="M3 6h7l2 3h9v11H3z"/>',text:'<path d="M3 4h18M12 4v17M8 21h8M3 4v4M21 4v4"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',image:'<rect x="3" y="3" width="18" height="18"/><path d="m3 17 6-6 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.4"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter" aria-hidden="true">${svgPaths[n]||svgPaths.website}</svg>`;
const bannerNames=['RCB brake master cylinder','Frando brake systems','Adelin master cylinder','RPD performance discs','Faito brake pads','Jomthai chain & sprocket','Tobaki ignition','NLK performance','FNM lighting','Fakie footrests'];
function home(){const tasks=[['photos','Change a banner','Fresh photo. Fresh first impression.','banners'],['price','Update a price','Change prices or add a discount.','prices'],['plus','Add a product','Put something new on your shelf.','new-product'],['services','Edit a service','Update what you do, and what it costs.','services'],['text','Edit website text','Say it your way, in a few clicks.','content'],['menu','Change the menu','Make everything easy to find.','menu']];return `${heading('YOUR STORE. YOUR WAY.','Your website, in your hands.','A new photo. A new price. A whole new offer. Start with what you want to change.','<span class="welcome-tag"><i></i> English workspace</span>')}
 <div class="overview-strip"><div><strong>${data.products.length}</strong><span>products on your shelf<small>CURRENT SITE INVENTORY</small></span></div><div><strong>${data.banners.length}</strong><span>campaign banners<small>READY TO MAKE YOURS</small></span></div><div><strong>${data.blocks.length}</strong><span>service & shop blocks<small>ONE PLACE TO EDIT</small></span></div></div>
 <div class="home-columns"><section><div class="section-caption"><h2>What would you like to change?</h2><span>Pick a task to get started ↙</span></div><div class="task-grid">${tasks.map((t,i)=>`<button class="task-card ${i===0?'featured':''}" data-task="${t[3]}"><span class="task-icon">${icon(t[0])}</span><span class="arrow">↗</span><b>${t[1]}</b><small>${t[2]}</small></button>`).join('')}</div></section><section class="site-card-column"><div class="section-caption"><h2>Your website</h2><span>DRAFT PREVIEW</span></div><div class="site-card"><div class="browser-chrome"><i></i><i></i><i></i><span>MOTO MARKET / HOME</span></div>${sitePreview()}<div class="site-card-foot"><span>Everything here is editable.</span><button data-route="website" data-sub="content">Open website editor ↗</button></div></div><div class="safe-note">${icon('shield')}<span>Make yourself at home. Save a draft, check how it looks, then publish when you’re ready.</span></div></section></div>
 <div class="bottom-columns"><section class="panel"><div class="panel-head"><h2>Your latest changes</h2><button data-action="review">See all →</button></div>${changes.length?changes.slice(-2).map(c=>`<div class="history-row">${esc(c.label)}<small>${esc(c.detail)} · Saved as draft</small></div>`).join(''):`<div class="empty-inline">${icon('clock')}<span>A clean slate. Make your first change.<small>Your edits will appear here before you publish.</small></span></div>`}</section><section class="panel"><div class="panel-head"><h2>One place for everything.</h2></div><button class="guide-link" data-route="photos"><b>01</b><span>Every photo, banner & icon</span><span>↗</span></button><button class="guide-link" data-route="products" data-sub="categories"><b>02</b><span>Every category & collection</span><span>↗</span></button><button class="guide-link" data-route="settings"><b>03</b><span>Your details, hours & links</span><span>↗</span></button></section></div>`;}
import {db,admin,live,upload} from '../cms/backend.js';
let staffList=[];
const roleName=role=>({owner:'Administrator',editor:'Content Manager',service:'Service Coordinator'}[role]||role);
function publishing(){return heading('YOUR STORIES. YOUR STYLE.','Pages & Posts','Build a page with HTML and CSS, or write a post using your store’s ready-made template.')+`<div class="toolbar"><h2>Website pages</h2>${addButton('page','Create page')}</div>${ordered('page',data.pages)}<div class="toolbar"><h2>Posts</h2>${addButton('post','Create post')}</div>${data.posts.length?ordered('post',data.posts):'<div class="empty-inline">Your first story starts here. Add a title, cover picture and the words. We take care of the layout.</div>'}<p class="small-note">After publishing, link to a new page or post from Website → Website menu.</p>`;}
function editStaff(id){const s=staffList.find(s=>s.user_id===id);if(!s)return;modal('MANAGE STAFF ACCESS',`<h2>Edit ${esc(s.display_name)}</h2><form id="staff-edit-form" data-id="${s.user_id}">${field('name','Staff name',s.display_name,'text','required')}${field('username','Username',s.username,'text','required pattern="[a-z][a-z0-9_-]{2,29}"')}${select('role','Role',s.role,[['owner','Administrator — full access'],['editor','Content Manager — website content'],['service','Service Coordinator — requests']])}${check('canPublish','Allow this Content Manager to publish',s.can_publish)}${field('password','New password (leave empty to keep current)','','password','minlength="14" autocomplete="new-password"')}<p class="small-note">Existing passwords are never displayed. Enter a new password to reset access.</p><button class="btn primary">Save access changes</button></form>`);}
const clone=v=>structuredClone(v);
let data,published,version,changes=[],history=[],inbox=[],media=[],mediaUrls={},staff,route='home',view='banners',productsView='products',servicesView='services',editorState,toastTimer,busy=false;
const labels={home:'Home',products:'Products',services:'Services',website:'Website',photos:'Photos',requests:'Requests',settings:'Store settings',publishing:'Pages & Posts'};
const collections={product:'products',category:'categories',service:'services',banner:'banners',block:'blocks',brand:'brands',vehicle:'vehicles',content:'content',page:'pages',menu:'menu',kit:'kits',post:'posts'};
const categoryName=id=>data.categories.find(c=>c.id===id)?.name||id;
const imageUrl=ref=>ref?.startsWith('media:')?mediaUrls[ref.slice(6)]||'':ref?.startsWith('assets/')?'../'+ref:ref||'';
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function fillIcons(){$$('[data-icon]').forEach(x=>x.innerHTML=icon(x.dataset.icon));}
function heading(k,title,description,action=''){return `<div class="page-heading"><div><span class="eyebrow red">${esc(k)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;}
function modal(kicker,html){$('#modal-kicker').textContent=kicker;$('#modal-body').innerHTML=html;const title=$('#modal-body h2');if(title)title.id='modal-title';if(!$('#modal').open)$('#modal').showModal();}
function errorMessage(error){toast(error.message||'Unable to save. Please try again.');if(error.code==='CONFLICT')modal('NEWER CHANGES FOUND','<h2>Your draft needs a refresh.</h2><p>Another staff member saved first. Your form stays open so you can copy your changes. Close it and reload the latest draft before trying again.</p><button class="btn primary" data-action="reload">Reload latest draft</button>');}
async function run(task){if(busy)return;busy=true;document.body.classList.add('is-busy');$$('button[type="submit"]').forEach(b=>b.disabled=true);try{await task();}catch(e){errorMessage(e);}finally{busy=false;document.body.classList.remove('is-busy');$$('button[type="submit"]').forEach(b=>b.disabled=false);}}
async function load(){const r=await admin('load');staff=r.staff;inbox=r.requests||[];media=r.media||[];mediaUrls=r.mediaUrls||{};data=r.draft?.content;if(data)data.posts||=[];version=r.draft?.version;changes=r.draft?.changes||[];published=r.live?.content;history=r.revisions||[];if(!data)route='requests';$('#login-screen').hidden=true;document.body.classList.remove('signed-out');$('.owner-label').textContent=roleName(staff.role);$('.profile-name').textContent=staff.display_name;$('.demo-bar span').innerHTML='<b>CONNECTED WORKSPACE</b> Save a draft. Preview it. Publish when ready.';$('.publish-button').hidden=!data;$('.preview-button').hidden=!data;render();}
async function save(next,key,label,detail=''){const list=clone(changes);const item={key,label,detail};const i=list.findIndex(c=>c.key===key);if(i<0)list.push(item);else list[i]=item;const r=await admin('save',{version,content:next,changes:list});data=next;version=r.version;changes=list;render();const frame=$('#preview-window iframe');if(frame)frame.src='../index.html?preview=draft&version='+version;toast('Draft saved. Your live website changes when you publish.');}
function go(to,sub){route=labels[to]?to:'home';if(!data)route='requests';if(sub){if(to==='website')view=sub;if(to==='products')productsView=sub;if(to==='services')servicesView=sub;}location.hash=route;$('#sidebar').classList.remove('open');render();}
function render(){const available=data?Object.entries(labels):Object.entries(labels).filter(([id])=>id==='requests'||id==='settings');$('#navigation').innerHTML=available.map(([id,name])=>`<button data-route="${id}" class="${route===id?'active':''}" ${route===id?'aria-current="page"':''}>${icon(id)}<span>${name}</span>${id==='requests'?`<span class="nav-meta">${inbox.filter(r=>r.status==='new').length}</span>`:''}</button>`).join('');$('#crumb-title').textContent=labels[route];$('#change-count').textContent=changes.length;$('#main').innerHTML=({home,products,services,website,photos,requests,settings,publishing}[route]||home)();fillIcons();}
function sitePreview(source=data){const b=source.banners.find(b=>b.visible),s=source.services.filter(s=>s.visible).slice(0,3);return `<div class="mini-site"><div class="mini-header"><img src="${esc(imageUrl(source.settings.logo))}" alt="${esc(source.settings.name)}"><span>PARTS · SERVICE · GEAR</span></div>${b?`<div class="mini-banner"><img src="${esc(imageUrl(b.image))}" alt="${esc(b.alt)}"><button class="edit-overlay" data-edit="banner" data-id="${b.id}">${icon('edit')} Change banner</button></div>`:''}<div class="mini-intro"><span class="eyebrow">YOUR STORE. ALWAYS UP TO DATE.</span><h3>${esc(source.settings.slogan)}</h3><div class="mini-blocks">${s.map(x=>`<div><img src="${esc(imageUrl(x.image))}" alt="">${esc(x.name)}</div>`).join('')}</div></div></div>`;}
function addButton(type,label){return `<button class="btn primary" data-edit="${type}" data-id="new">${icon('plus')} ${esc(label)}</button>`;}
function tabs(items,current,target){return '<div class="subtabs">'+items.map(([id,title])=>`<button data-route="${target}" data-sub="${id}" class="${current===id?'active':''}">${title}</button>`).join('')+'</div>';}
function ordered(type,list){return `<div class="section-list">${list.map((p,i)=>`<div class="section-row">${p.image?`<img class="list-art" src="${esc(imageUrl(p.image))}" alt="">`:`<span class="section-number">${String(i+1).padStart(2,'0')}</span>`}<div><h3>${esc(p.name)}</h3><p>${esc(p.hint||p.description||p.page||'')}${p.visible===false?' · Hidden':''}</p></div><div class="row-actions"><button class="icon-button" data-order="${type}" data-index="${i}" data-dir="-1" aria-label="Move ${esc(p.name)} up" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-order="${type}" data-index="${i}" data-dir="1" aria-label="Move ${esc(p.name)} down" ${i===list.length-1?'disabled':''}>↓</button><button class="btn tiny ghost" data-edit="${type}" data-id="${p.id}">Edit</button></div></div>`).join('')}</div>`;}
function productRows(list){return list.length?list.map(p=>`<div class="product-row"><div class="product-main"><div class="product-img"><img src="${esc(imageUrl(p.image))}" alt=""></div><div><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${esc(p.stock)}</small></div></div><div class="category">${esc(categoryName(p.category))}</div><div class="price"><b>${money(p.sale||p.price)}</b>${p.sale?`<del>${money(p.price)}</del>`:''}</div><div class="status-col"><span class="status ${p.visible?'':'draft'}">${p.visible?'Visible':'Hidden'}</span></div><button class="text-button" data-edit="product" data-id="${p.id}">Edit</button></div>`).join(''):'<p class="empty-inline">Nothing found. Try another name or category.</p>';}
function products(){return heading('YOUR SHOP','Products','Edit once. Prices, pictures and discounts update across your website.',addButton('product','Add product'))+tabs([['products','All products'],['categories','Categories'],['kits','Bundles'],['vehicles','Bikes & cars']],productsView,'products')+(productsView==='categories'?ordered('category',data.categories)+addButton('category','Add category'):productsView==='kits'?ordered('kit',data.kits)+addButton('kit','Add bundle'):productsView==='vehicles'?ordered('vehicle',data.vehicles)+addButton('vehicle','Add vehicle'):`<div class="toolbar"><div class="toolbar-group"><label class="search-box">${icon('search')}<input id="product-search" type="search" aria-label="Find a product" placeholder="Find a product…"></label><select id="product-category" aria-label="Filter category"><option value="">All categories</option>${data.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><span>${data.products.length} products</span></div><div class="product-list"><div class="product-row header"><span>Product</span><span class="category">Category</span><span>Customer pays</span><span class="status-col">On website</span><span></span></div><div id="product-rows">${productRows(data.products)}</div></div>`);}
function services(){return heading('THE WORKSHOP','Services','Make every service easy to understand and book.',addButton('service','Add service'))+tabs([['services','Services'],['categories','Service categories'],['blocks','Homepage blocks']],servicesView,'services')+(servicesView==='categories'?`<div class="panel settings-layout"><h2>Services menu</h2><p>One category per line. The order here is the order on your website.</p><form id="service-categories-form">${textarea('categories','Service categories',data.serviceCategories.join('\n'))}<button class="btn primary">Save draft →</button></form></div>`:servicesView==='blocks'?ordered('block',data.blocks)+addButton('block','Add homepage block'):`<div class="service-grid">${data.services.map(s=>`<article class="service-card"><img src="${esc(imageUrl(s.image))}" alt=""><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><div class="service-card-foot"><span>${s.visible?s.mode==='Fixed price'?money(s.price):'Price by quote':'Hidden'}</span><button class="btn tiny ghost" data-edit="service" data-id="${s.id}">Edit service ↗</button></div></article>`).join('')}</div>`);}
function website(){return heading('MAKE IT YOURS','Your website','Find the part you want to change. The layout takes care of itself.')+tabs([['banners','Banners'],['content','Page content'],['menu','Website menu'],['logos','Brand logos'],['pages','Search & sharing'],['history','Version history']],view,'website')+(view==='banners'?`<div class="toolbar"><p>Use the arrows to change the slideshow order.</p>${addButton('banner','Add banner')}</div>${ordered('banner',data.banners)}`:view==='content'?`<div class="info-banner">${icon('text')}<span>Every section includes its text, pictures and links. Changes stay private until published.</span></div>${ordered('content',data.content)}`:view==='menu'?ordered('menu',data.menu)+addButton('menu','Add menu link'):view==='logos'?ordered('brand',data.brands)+addButton('brand','Add brand'):view==='pages'?ordered('page',data.pages):`<div class="info-banner">${icon('clock')}<span>Restore a previous website version. This replaces your current draft and live content. Customer requests and staff accounts stay as they are.</span></div>${history.map(r=>`<div class="section-row"><div><h3>${esc(r.summary)}</h3><p>${esc(new Date(r.created_at).toLocaleString())}</p></div>${staff.role==='owner'?`<button class="btn ghost" data-restore="${r.id}">Restore…</button>`:''}</div>`).join('')}`);}
function photoItems(){const items=[...media.map(m=>({id:m.id,name:m.name,image:'media:'+m.id,usage:'Uploaded picture'}))];for(const key of ['banners','products','services','blocks','brands','categories'])for(const p of data[key]||[])if(p.image&&!items.some(x=>x.image===p.image))items.push({id:p.id,name:p.name,image:p.image,usage:key});return items;}
function photos(){return heading('YOUR PHOTO LIBRARY','A place for every picture.','Upload a photo once, then choose it wherever you need it. JPG, PNG or WebP, up to 5 MB.',`<button class="btn primary" data-action="upload-library">${icon('upload')} Upload a photo</button>`)+`<div class="media-grid">${photoItems().map((p,i)=>`<button class="media-card" data-photo="${i}"><div class="media-art"><img loading="lazy" src="${esc(imageUrl(p.image))}" alt="${esc(p.name)}"></div><b>${esc(p.name)}</b><small>${esc(p.usage)}</small></button>`).join('')}</div>`;}
function requests(){return heading('THE DAILY WORK','Orders & bookings','New customer requests are saved here. Contact the customer before confirming.',`<button class="btn ghost" data-action="reload">Refresh inbox</button>`)+(inbox.length?inbox.map(r=>`<div class="section-row"><span class="status ${r.status==='new'?'draft':''}">${esc(r.status)}</span><div><h3>${esc(r.customer_name)} · ${esc(r.kind)}</h3><p>${esc(r.receipt)} · ${esc(new Date(r.created_at).toLocaleString())}</p></div><button class="btn ghost" data-request="${r.id}">Open request →</button></div>`).join(''):`<div class="empty-state">${icon('requests')}<h2>Ready for your first request.</h2><p>Customers can send product requests from their cart, or book a service from the booking page.</p><a class="btn ghost" href="../book.html" target="_blank" rel="noopener">Open booking page ↗</a></div>`);}
function settings(){const s=data?.settings;return heading('THE ESSENTIALS','Store settings','Your shop details and your team, all in one place.')+(s?`<form id="settings-form" class="panel settings-layout"><h2>Business details</h2><div class="settings-grid">${[['name','Store name'],['slogan','Tagline'],['phone','Phone number'],['whatsapp','WhatsApp number'],['email','Email address'],['hours','Opening hours'],['address','Store address'],['facebook','Facebook link'],['map','Map link']].map(([key,label])=>field(key,label,s[key],key==='email'?'email':'text')).join('')}</div><button class="btn primary">Save details as draft →</button><button class="btn ghost" type="button" data-edit="identity" data-id="settings">Change logo & browser icon</button></form>`:'')+`<div class="panel settings-layout"><h2>Your sign-in</h2><p>Signed in as ${esc(staff.username)} · ${esc(roleName(staff.role))}</p><form id="password-form">${field('password','New password','','password','minlength="14" maxlength="100" required autocomplete="new-password"')}<button class="btn ghost">Change my password</button></form><button class="btn ghost" data-action="signout">Sign out</button></div>${staff.role==='owner'?`<div class="panel settings-layout"><h2>Your team</h2><p>Choose who can edit the website, publish, or manage requests.</p><button class="btn primary" data-action="staff">Manage staff →</button></div>`:''}`;}
function field(name,label,value='',type='text',extra=''){return `<div class="field"><label for="field-${name}">${esc(label)}</label><input id="field-${name}" name="${name}" type="${type}" value="${esc(value??'')}" ${extra}></div>`;}
function textarea(name,label,value=''){return `<div class="field"><label for="field-${name}">${esc(label)}</label><textarea id="field-${name}" name="${name}" rows="4">${esc(value||'')}</textarea></div>`;}
function select(name,label,value,options){return `<div class="field"><label for="field-${name}">${esc(label)}</label><select id="field-${name}" name="${name}">${options.map(o=>{const [val,title]=Array.isArray(o)?o:[o,o];return `<option value="${esc(val)}" ${value===val?'selected':''}>${esc(title)}</option>`;}).join('')}</select></div>`;}
function check(name,label,value){return `<label class="switch-row"><span>${esc(label)}</span><input type="checkbox" name="${name}" ${value?'checked':''}></label>`;}
function colourRow(c){return `<div class="colour-editor-row" data-colour-row="${esc(c.id)}"><div class="field-columns">${field('colour-name-'+c.id,'Colour name',c.name,'text','required maxlength="60"')}${field('colour-hex-'+c.id,'Colour swatch',c.hex,'color')}${select('colour-stock-'+c.id,'Availability',c.stock,['In stock','Out of stock'])}</div>${photoField('colour:'+c.id,'Photo for this colour (optional)',c.image||'')}<button class="btn tiny ghost" type="button" data-remove-colour="${esc(c.id)}">Remove colour</button></div>`;}
function colourEditor(p){return '<h3>Available colours</h3><p class="small-note">Add each real colour, its availability and an optional photo. Leave this empty for products without colour options.</p><div id="colour-editor">'+(p.colors||[]).map(colourRow).join('')+'</div><button class="btn ghost" type="button" data-action="add-colour">+ Add colour</button>';}
function photoField(key,label,ref){return `<div class="image-editor"><label>${esc(label)}</label><img class="edit-image" data-picture="${key}" src="${esc(imageUrl(ref))}" alt="${esc(label)}"><div class="image-edit-actions"><button class="btn ghost" type="button" data-picture-choose="${key}">Choose photo</button><button class="btn ghost" type="button" data-picture-upload="${key}">Upload</button></div></div>`;}
const lineList=v=>String(v||'').split('\n').map(s=>s.trim()).filter(Boolean);
function defaults(type){const image='assets/icons/servicing.png',id=type+'-'+crypto.randomUUID();const basic={id,name:'',visible:true};return ({product:{...basic,brand:'',category:data.categories[0]?.id,subcategory:'',price:null,sale:null,image:'assets/icons/spare-parts.png',gallery:[],stock:'In stock',description:'',badge:'',featured:false,specifications:'',fitment:'Ask us to confirm',vehicleIds:[],vehicleTypes:[],colors:[]},category:{...basic,children:[],image,description:''},service:{...basic,image,description:'',included:[],category:data.serviceCategories[0]||'',mode:'Quote after inspection',price:null,duration:'Confirmed after inspection',booking:true},banner:{...basic,image:data.banners[0]?.image||image,mobileImage:'',alt:'',destination:'Home',focalX:50,focalY:50},block:{...basic,image,description:'',included:[],target:data.services[0]?.id,kind:'service',button:'View details'},brand:{...basic,image,group:'oil'},vehicle:{...basic,type:'bike',brand:''},menu:{...basic,target:'Home'},kit:{...basic,description:'',productIds:[]},page:{...basic,custom:true,title:'',description:'',shareImage:'assets/banners/frando-brakes.webp',slug:'',html:'<section class="section"><p class="label">MOTO MARKET</p><h1>Your new page</h1><p class="lede">Tell your story here.</p></section>',css:''},post:{...basic,slug:'',excerpt:'',body:'',image:'assets/banners/frando-brakes.webp',author:'Moto Market',date:new Date().toISOString().slice(0,10)}})[type];}
function openEditor(type,id){const isNew=id==='new';const p=clone(type==='identity'?data.settings:isNew?defaults(type):data[collections[type]]?.find(x=>x.id===id));if(!p){toast('This item could not be found.');return;}editorState={type,id,isNew,record:p};const options=data.categories.map(c=>[c.id,c.name]);const targets=[...options,['Services','Services'],['Home','Home'],['Contact','Contact'],['Posts','All posts'],...data.pages.map(p=>['page:'+p.id,p.name+' (page)']),...data.posts.map(p=>['post:'+p.id,p.name+' (post)'])];let h='';
 if(type==='content'){h=`<p class="small-note">${esc(p.page==='index'?'Home':p.page)} → ${esc(p.name)}</p>`+p.fields.map((f,i)=>f.kind==='image'?photoField('field:'+i,f.label,f.value):f.kind==='link'?field('content-'+i,f.label,f.value,'text','required'):textarea('content-'+i,f.label+' · '+f.value.slice(0,55),f.value)).join('');}
 else if(type==='identity')h=photoField('logo','Store logo',p.logo)+photoField('favicon','Browser icon',p.favicon);
 else if(type==='page')h=(p.custom?field('name','Page name',p.name,'text','required')+field('slug','Page address',p.slug,'text','required pattern="[a-z0-9]+(-[a-z0-9]+)*"'):'')+field('title','Page title',p.title,'text','required maxlength="200"')+textarea('description','Search description',p.description)+photoField('shareImage','Link sharing picture',p.shareImage)+(p.custom?'<p class="info-banner">Write HTML and CSS. The page uses the store fonts, colours and sharp corners. Scripts and forms are disabled inside custom page code.</p>'+textarea('html','Page HTML',p.html)+textarea('css','Page CSS',p.css)+check('visible','Visible on website',p.visible):'');
 else{h=field('name',type==='menu'?'Menu label':'Name',p.name,'text','required maxlength="150"');if(p.image!==undefined)h+=photoField('image',type==='banner'?'Banner picture':'Picture or icon',p.image);
  if(type==='post')h+=field('slug','Post address',p.slug,'text','required pattern="[a-z0-9]+(-[a-z0-9]+)*"')+field('author','Author',p.author)+field('date','Post date',p.date,'date','required')+textarea('excerpt','Introduction',p.excerpt)+textarea('body','Post content',p.body)+'<p class="small-note">Separate paragraphs with a blank line. Start a line with ## for a heading or - for a bullet. The Moto Market template handles the design.</p>';
  if(type==='product')h+=field('brand','Brand',p.brand)+select('category','Category',p.category,options)+select('subcategory','Subcategory',p.subcategory||'',[['','No subcategory'],...(data.categories.find(c=>c.id===p.category)?.children||[])])+`<div class="field-columns">${field('price','Regular price (৳)',p.price,'number','min="1" step="1" required')}${field('sale','Discount price (৳)',p.sale,'number','min="1" step="1"')}</div><p class="small-note">Leave the discount price empty for no discount.</p>`+select('stock','Availability',p.stock,['In stock','Out of stock','Ask us'])+textarea('description','Description',p.description)+textarea('specifications','Specifications',p.specifications)+field('badge','Short label (optional)',p.badge)+check('featured','Feature this product',p.featured)+select('fitment','Vehicle compatibility',p.fitment,['Ask us to confirm','Universal','Selected vehicles'])+`<fieldset class="check-list" data-compatible-models><legend>Compatible vehicles</legend><input type="search" data-model-check-search aria-label="Find a compatible model" placeholder="Find a model…">${data.vehicles.map(v=>`<label><input type="checkbox" name="vehicleIds" value="${v.id}" ${p.vehicleIds?.includes(v.id)?'checked':''}> ${esc(v.brand+' '+v.name)}</label>`).join('')}</fieldset>`+`<fieldset class="check-list" data-universal-types><legend>For universal products: vehicle types</legend>${[['bike','Bikes'],['car','Cars']].map(([id,label])=>`<label><input type="checkbox" name="vehicleTypes" value="${id}" ${p.vehicleTypes?.includes(id)?'checked':''}>${label}</label>`).join('')}</fieldset>`+colourEditor(p)+`<h3>Extra product photos</h3>${[0,1,2,3].map(i=>photoField('gallery:'+i,'Photo '+(i+2),p.gallery?.[i]||'')).join('')}`;
  if(type==='category')h+=textarea('description','Introduction',p.description)+textarea('children','Subcategories (one per line)',p.children.join('\n'));
  if(type==='service')h+=textarea('description','Description',p.description)+textarea('included','What is included (one per line)',p.included?.join('\n'))+select('category','Service category',p.category,data.serviceCategories)+select('mode','How is the price decided?',p.mode,['Quote after inspection','Fixed price'])+field('price','Fixed price (৳)',p.price,'number','min="1" step="1"')+field('duration','Time required',p.duration)+check('booking','Accept booking requests',p.booking!==false);
  if(type==='banner')h+=field('alt','Describe this banner',p.alt,'text','required maxlength="300"')+select('destination','Open this page when clicked',p.destination,targets)+photoField('mobileImage','Phone banner (optional)',p.mobileImage)+field('focalX','Horizontal image focus (0–100)',p.focalX,'number','min="0" max="100"')+field('focalY','Vertical image focus (0–100)',p.focalY,'number','min="0" max="100"');
  if(type==='block')h+=textarea('description','Description',p.description)+textarea('included','Details (one per line)',p.included?.join('\n'))+select('blockTarget','Open this service or category',p.kind+':'+p.target,[...data.services.map(s=>['service:'+s.id,s.name+' (service)']),...options.map(([id,n])=>['category:'+id,n+' (shop)'])])+field('button','Button text',p.button);
  if(type==='brand')h+=field('alt','Logo description',p.alt||p.name)+select('group','Display group',p.group,[['oil','Engine oil'],['tyres','Tyres']]);
  if(type==='vehicle')h+=select('type','Vehicle type',p.type,[['bike','Bike'],['car','Car']])+field('brand','Manufacturer',p.brand,'text','required');
  if(type==='menu')h+=select('target','Where does this link go?',p.target,targets);
  if(type==='kit')h+=textarea('description','Description',p.description)+`<fieldset class="check-list"><legend>Products in this bundle (prices stay connected)</legend>${data.products.map(x=>`<label><input type="checkbox" name="productIds" value="${x.id}" ${p.productIds.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join('')}</fieldset>`;
 }
 if(!['page','identity'].includes(type))h+=check('visible','Visible on website',p.visible!==false);$('#editor-title').textContent=isNew?'Add '+type:p.name||'Store identity';$('#editor-kicker').textContent='EDIT '+type.toUpperCase();$('#editor-body').innerHTML=h;$$('[name=html],[name=css]').forEach(x=>x.classList.add('code-editor'));$('#editor').showModal();updateCompatibilityFields();}
async function saveEditor(e){e.preventDefault();await run(async()=>{const {type,isNew,record:p}=editorState;const f=new FormData(e.target),v=n=>String(f.get(n)||'').trim();const next=clone(data);if(type==='content'){p.fields.forEach((x,i)=>{if(x.kind!=='image')x.value=v('content-'+i);});}else if(type==='page'){p.title=v('title');p.description=v('description');if(p.custom){p.name=v('name');p.slug=v('slug');p.html=v('html');p.css=v('css');p.visible=f.has('visible');}}else if(type!=='identity'){p.name=v('name');for(const key of ['brand','category','subcategory','description','specifications','badge','stock','fitment','mode','duration','alt','destination','group','target','button','alt'])if(f.has(key))p[key]=v(key);for(const key of ['price','sale'])if(f.has(key))p[key]=v(key)===''?null:Number(v(key));for(const key of ['focalX','focalY'])if(f.has(key))p[key]=Number(v(key));for(const key of ['featured','booking'])if(type==='product'&&key==='featured'||type==='service'&&key==='booking')p[key]=f.has(key);if(type==='product'){p.vehicleIds=f.getAll('vehicleIds');p.vehicleTypes=f.getAll('vehicleTypes');p.colors=(p.colors||[]).map(c=>({...c,name:v('colour-name-'+c.id),hex:v('colour-hex-'+c.id),stock:v('colour-stock-'+c.id)}));p.gallery=(p.gallery||[]).filter(Boolean);}if(f.has('included'))p.included=lineList(v('included'));if(type==='category'){const old=data.categories.find(x=>x.id===p.id);p.children=lineList(v('children'));next.products.filter(x=>x.category===p.id&&x.subcategory&&!p.children.includes(x.subcategory)).forEach(x=>{const index=old?.children.indexOf(x.subcategory);x.subcategory=p.children[index]||'';});}if(type==='post'){for(const k of ['slug','author','date','excerpt','body'])p[k]=v(k);}if(type==='vehicle')p.type=v('type');if(type==='block'){[p.kind,p.target]=v('blockTarget').split(':');}if(type==='kit')p.productIds=f.getAll('productIds');}
 if(!['page','identity'].includes(type))p.visible=f.has('visible');if(type==='identity')next.settings=p;else{const list=next[collections[type]];if(isNew)list.push(p);else list[list.findIndex(x=>x.id===p.id)]=p;}await save(next,type+'-'+(p.id||'store'),'Updated '+(p.name||'store identity'));$('#editor').close();editorState=null;});}
function setPicture(key,ref){const p=editorState.record;if(key.startsWith('field:'))p.fields[Number(key.split(':')[1])].value=ref;else if(key.startsWith('gallery:')){p.gallery||=[];p.gallery[Number(key.split(':')[1])]=ref;}else if(key.startsWith('colour:')){const c=p.colors?.find(c=>c.id===key.slice(7));if(c)c.image=ref;}else p[key]=ref;const img=$(`[data-picture="${CSS.escape(key)}"]`);if(img)img.src=imageUrl(ref);}
function chooseImage(key){editorState.pictureKey=key;modal('YOUR PHOTO LIBRARY',`<h2>Choose a picture.</h2><div class="photo-choices">${photoItems().map((p,i)=>`<button class="photo-choice" data-pick="${i}"><img src="${esc(imageUrl(p.image))}" alt=""><span>${esc(p.name)}</span></button>`).join('')}</div>`);}
function review(){modal('REVIEW BEFORE PUBLISHING',`<h2>${changes.length?changes.length+' changes. Ready when you are.':'You’re all up to date.'}</h2><p>Publishing makes these saved changes visible to everyone.</p>${changes.map(c=>`<div class="review-row">${icon('check')}<div>${esc(c.label)}<small>${esc(c.detail)}</small></div></div>`).join('')}<div class="modal-footer"><button class="btn ghost" data-action="preview">Preview first</button>${changes.length&&(staff.role==='owner'||staff.can_publish)?'<button class="btn primary" data-action="publish">Publish website →</button>':''}</div>${staff.role!=='owner'&&!staff.can_publish?'<p>Ask the store owner to publish your saved changes.</p>':''}`);}
async function publish(){await run(async()=>{const r=await admin('publish',{version});const current=await live();if(current.revision!==r.revision)throw new Error('Publication needs another check. Refresh before continuing.');await load();modal('WEBSITE UPDATED',`<span class="success-mark">${icon('check')}</span><h2>Your changes are live.</h2><p>Your website is now showing this published version. You can restore an earlier version from Website → Version history.</p><a class="btn primary" href="../index.html?v=${encodeURIComponent(r.revision)}" target="_blank" rel="noopener">See your website ↗</a>`);});}
function preview(){modal('SAVED DRAFT PREVIEW','<h2>See it before everyone else.</h2><p>This is your real website using the saved draft. Unsaved form edits are not included.</p><div class="device-tabs"><button class="btn tiny active" data-device="desktop">Desktop</button><button class="btn tiny" data-device="phone">Phone</button></div><div id="preview-window" class="preview-window"><iframe title="Saved website draft" src="../index.html?preview=draft"></iframe></div><a class="btn ghost" href="../shop.html?preview=draft" target="_blank" rel="noopener">Preview shop ↗</a> <a class="btn ghost" href="../book.html?preview=draft" target="_blank" rel="noopener">Preview booking ↗</a>');}
function help(){modal('A LITTLE GUIDANCE','<h2>You’ve got this.</h2><div class="guide-step"><b>01</b><div><h3>Choose what to change</h3><p>Start from Home, or choose Products, Services or Website.</p></div></div><div class="guide-step"><b>02</b><div><h3>Save your draft</h3><p>Type your new details or choose a photo. Save. Your customers still see the previous version.</p></div></div><div class="guide-step"><b>03</b><div><h3>Preview. Publish. Done.</h3><p>Check your draft and use Review & publish. Version history lets the owner undo a publication.</p></div></div>');}
function search(){modal('FIND YOUR WAY','<h2>What are you looking for?</h2><label class="search-box"><input type="search" id="global-search" aria-label="Search control room" placeholder="Product, banner, page or service…"></label><div id="global-results"></div>');searchResults('');$('#global-search').focus();}
function searchResults(q){const all=[...Object.entries(labels).map(([id,name])=>({id,name,route:id})),...Object.entries(collections).flatMap(([type,key])=>(data?.[key]||[]).map(x=>({...x,type})))];$('#global-results').innerHTML=all.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).slice(0,20).map(x=>`<button class="search-result" ${x.route?`data-route="${x.route}"`:`data-edit="${x.type}" data-id="${x.id}"`}>${esc(x.name)}<small>${esc(x.type||'Workspace')} ↗</small></button>`).join('')||'<p>No matches found.</p>';}
function openRequest(id){const r=inbox.find(x=>x.id===id);if(!r)return;const d=r.details;modal('REQUEST '+r.receipt,`<h2>${esc(r.customer_name)}</h2><p><a href="tel:${esc(r.phone)}">${esc(r.phone)}</a> · ${esc(r.kind)}</p><p>${esc(d.vehicle||'')}</p>${d.items?d.items.map(i=>`<div class="review-row">${esc(i.name)}${i.colorName?' · '+esc(i.colorName):''} × ${i.quantity}<strong>${money(i.quantity*i.unitPriceMinor/100)}</strong></div>`).join('')+`<h3>Total ${money(d.totalMinor/100)}</h3>`:`<p>${esc(d.services?.map(s=>s.name).join(', '))}</p><p>Preferred: ${esc(d.date||'Any day')} · ${esc(d.slot||'Any time')}</p>`}<p>${esc(d.notes||'No customer notes.')}</p><form id="request-form" data-id="${r.id}">${select('status','Request status',r.status,['new','contacted','confirmed','completed','cancelled'])}${textarea('notes','Staff notes (private)',r.staff_notes)}<button class="btn primary">Save request update</button></form>`);}
async function team(){const r=await admin('staff-list');staffList=r.staff;modal('STAFF ACCESS',`<h2>Your team.</h2>${r.staff.map(s=>`<div class="section-row"><div><h3>${esc(s.display_name)}</h3><p>${esc(s.username)} · ${esc(roleName(s.role))} · ${s.active?'Active':'Disabled'}</p></div><button class="btn ghost" data-staff-edit="${s.user_id}">Edit access</button>${s.user_id!==staff.user_id?`<button class="btn ghost" data-staff-toggle="${s.user_id}" data-disabled="${s.active}">${s.active?'Disable':'Enable'}</button>`:''}</div>`).join('')}<h3>Add a staff member</h3><form id="staff-form">${field('name','Staff name','','text','required')}${field('username','Username','','text','pattern="[a-z][a-z0-9_-]{2,29}" required autocomplete="off"')}${field('password','Temporary password','','password','minlength="14" required autocomplete="new-password"')}${select('role','Access level','editor',[['editor','Content Manager — edit website'],['service','Service Coordinator — requests'],['owner','Administrator — full access']])}${check('canPublish','Allow this editor to publish',false)}<p class="small-note">Share the username and temporary password privately. They can change their password in Store settings.</p><button class="btn primary">Create staff account</button></form>`);}
function showLogin(message=''){document.body.classList.add('signed-out');$('#login-screen').hidden=false;$('#login-message').textContent=message;}
$('#login-form').addEventListener('submit',e=>{e.preventDefault();run(async()=>{const f=new FormData(e.target),username=String(f.get('username')).trim().toLowerCase();const {error}=await db.auth.signInWithPassword({email:username+'@staff.motomarket.invalid',password:String(f.get('password'))});if(error){$('#login-message').textContent='Check your username and password, then try again.';return;}await load();e.target.reset();});});
$('#editor-form').addEventListener('submit',saveEditor);
document.addEventListener('submit',e=>{const id=e.target.id;if(['settings-form','service-categories-form','password-form','request-form','staff-form','staff-edit-form'].includes(id)){e.preventDefault();run(async()=>{const f=new FormData(e.target);if(id==='settings-form'){const next=clone(data);for(const [k,v] of f)next.settings[k]=String(v).trim();await save(next,'settings','Updated store details');}if(id==='service-categories-form'){const next=clone(data),list=lineList(f.get('categories'));if(!list.length)throw new Error('Keep at least one service category.');next.services.forEach(s=>{if(!list.includes(s.category))s.category=list[next.serviceCategories.indexOf(s.category)]||list[0];});next.serviceCategories=list;await save(next,'service-categories','Updated service categories');}if(id==='password-form'){const {error}=await db.auth.updateUser({password:String(f.get('password'))});if(error)throw error;e.target.reset();toast('Your password has been changed.');}if(id==='request-form'){const r=inbox.find(r=>r.id===e.target.dataset.id);await admin('request-update',{id:r.id,version:r.version,status:f.get('status'),notes:f.get('notes')});await load();$('#modal').close();toast('Request updated.');}if(id==='staff-edit-form'){await admin('staff-update',{userId:e.target.dataset.id,name:f.get('name'),username:f.get('username'),password:f.get('password'),role:f.get('role'),canPublish:f.has('canPublish')});await team();toast('Staff access updated.');}if(id==='staff-form'){await admin('staff-create',{name:f.get('name'),username:f.get('username'),password:f.get('password'),role:f.get('role'),canPublish:f.has('canPublish')});await team();toast('Staff account created.');}});}});
document.addEventListener('input',e=>{if(e.target.id==='global-search')searchResults(e.target.value);if(e.target.id==='product-search')filterProducts();});
function filterProducts(){const q=$('#product-search').value.toLowerCase(),cat=$('#product-category').value;$('#product-rows').innerHTML=productRows(data.products.filter(p=>(p.name+' '+p.brand).toLowerCase().includes(q)&&(!cat||p.category===cat)));}
document.addEventListener('change',e=>{if(e.target.id==='product-category')filterProducts();if(e.target.id==='field-category'&&editorState?.type==='product'){$('#field-subcategory').innerHTML='<option value="">No subcategory</option>'+(data.categories.find(c=>c.id===e.target.value)?.children||[]).map(n=>`<option>${esc(n)}</option>`).join('');}});
$('#image-upload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const key=e.target.dataset.picture;run(async()=>{const r=await upload(file);media.unshift(r.media);mediaUrls[r.media.id]=r.url;if(key&&editorState){setPicture(key,'media:'+r.media.id);toast('Picture uploaded. Save this draft to use it.');}else{render();toast('Picture added to your library.');}});});
document.addEventListener('click',e=>{const b=e.target.closest('button,a[data-route]');if(!b)return;const d=b.dataset;
 if(d.route){$('#modal').close();go(d.route,d.sub);return;}if(d.task){const map={banners:['website','banners'],prices:['products','products'],services:['services','services'],content:['website','content'],menu:['website','menu']};if(d.task==='new-product')openEditor('product','new');else go(...map[d.task]);return;}
 if(d.edit){$('#modal').close();openEditor(d.edit,d.id);return;}if(d.order){run(async()=>{const next=clone(data),list=next[collections[d.order]],i=Number(d.index),j=i+Number(d.dir);if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];await save(next,d.order+'-order','Reordered '+collections[d.order]);});return;}
 if(d.pictureChoose){chooseImage(d.pictureChoose);return;}if(d.pictureUpload){$('#image-upload').dataset.picture=d.pictureUpload;$('#image-upload').value='';$('#image-upload').click();return;}if(d.pick!==undefined){setPicture(editorState.pictureKey,photoItems()[Number(d.pick)].image);$('#modal').close();return;}if(d.photo!==undefined){const p=photoItems()[Number(d.photo)];const usages=[];for(const [key,items] of Object.entries(data))if(Array.isArray(items))items.forEach(item=>{if(JSON.stringify(item).includes(JSON.stringify(p.image)))usages.push(item.name||key);});modal('PHOTO DETAILS',`<h2>${esc(p.name)}</h2><img class="photo-detail" src="${esc(imageUrl(p.image))}" alt="${esc(p.name)}"><p>Used in: ${esc([...new Set(usages)].join(', ')||'Ready to use — no current placements')}</p>`);return;}
 if(d.device){$('#preview-window').classList.toggle('phone',d.device==='phone');return;}if(d.request){openRequest(d.request);return;}if(d.restore){modal('RESTORE WEBSITE VERSION',`<h2>Restore this version?</h2><p>This replaces both the saved draft and the public website. The current publication remains in history, so you can bring it back.</p><button class="btn ghost" data-action="close-modal">Keep current version</button> <button class="btn primary" data-confirm-restore="${d.restore}">Restore version</button>`);return;}if(d.confirmRestore){run(async()=>{await admin('restore',{version,revision:d.confirmRestore});await load();$('#modal').close();toast('Website restored to the selected version.');});return;}
 if(d.staffEdit){editStaff(d.staffEdit);return;}if(d.staffToggle){run(async()=>{await admin('staff-disable',{userId:d.staffToggle,disabled:d.disabled==='true'});await team();});return;}
 if(d.removeColour){editorState.record.colors=editorState.record.colors.filter(c=>c.id!==d.removeColour);$(`[data-colour-row="${CSS.escape(d.removeColour)}"]`).remove();return;}const action=d.action;if(action==='add-colour'){const c={id:'colour-'+crypto.randomUUID(),name:'',hex:'#dc1238',stock:'In stock',image:''};editorState.record.colors||=[];editorState.record.colors.push(c);$('#colour-editor').insertAdjacentHTML('beforeend',colourRow(c));$(`[name="colour-name-${c.id}"]`).focus();return;}if(action==='menu')$('#sidebar').classList.toggle('open');if(action==='close-editor'){$('#editor').close();editorState=null;}if(action==='close-modal')$('#modal').close();if(action==='help')help();if(action==='search')search();if(action==='review')review();if(action==='publish')publish();if(action==='preview')preview();if(action==='reload')run(async()=>{await load();$('#modal').close();$('#editor').close();toast('Latest saved content loaded.');});if(action==='staff')run(team);if(action==='upload-library'){$('#image-upload').dataset.picture='';$('#image-upload').value='';$('#image-upload').click();}if(action==='signout')run(async()=>{await db.auth.signOut();data=null;showLogin();});
});
window.addEventListener('hashchange',()=>{if(staff){const next=location.hash.slice(1);if(labels[next]&&next!==route)go(next);}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&staff&&!$('#editor').open&&!$('#modal').open){e.preventDefault();search();}});
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){staff=null;data=null;showLogin();}});
route=labels[location.hash.slice(1)]?location.hash.slice(1):'home';fillIcons();
try{const {data:{session}}=await db.auth.getSession();if(session)await load();else showLogin();}catch(e){showLogin(e.message);}

let syncBusy=false;
async function syncWorkspace(){if(!staff||busy||syncBusy||document.hidden||$('#editor').open||$('#modal').open)return;syncBusy=true;try{const r=await admin('sync');staff=r.staff;inbox=r.requests||[];if(data&&r.version!==version){await load();toast('The latest saved changes from your team are now loaded.');}else if(route==='requests')render();else{const counter=$('[data-route="requests"] .nav-meta');if(counter)counter.textContent=inbox.filter(x=>x.status==='new').length;}}catch(e){if(/access|sign in/i.test(e.message)){staff=null;data=null;showLogin(e.message);}}finally{syncBusy=false;}}
setInterval(syncWorkspace,30000);document.addEventListener('visibilitychange',syncWorkspace);window.addEventListener('online',syncWorkspace);

function updateCompatibilityFields(){const method=$('[name=fitment]')?.value,models=$('[data-compatible-models]'),types=$('[data-universal-types]');if(models)models.hidden=method!=='Selected vehicles';if(types)types.hidden=method!=='Universal';}
document.addEventListener('change',e=>{if(e.target.name==='fitment')updateCompatibilityFields();});document.addEventListener('input',e=>{if(e.target.matches('[data-model-check-search]')){$$('label',e.target.closest('fieldset')).forEach(l=>l.hidden=!l.textContent.toLowerCase().includes(e.target.value.toLowerCase()));}});
