export const PROJECT_URL='https://ttpzdsecwhufzahtoyrp.supabase.co';
export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function assert(ok,message){if(!ok)throw new Error(message);}
export function text(value,label,max=5000,required=false){assert(typeof value==='string'&&value.length<=max,`${label} must be text under ${max} characters.`);assert(!required||value.trim().length>0,`${label} is required.`);return value.trim();}
export function imageRef(value,optional=false){if(optional&&!value)return true;return typeof value==='string'&&((/^assets\/[a-zA-Z0-9_./-]+\.(png|webp|jpe?g)$/i.test(value)&&!value.includes('..'))||/^media:[0-9a-f-]{36}$/i.test(value));}
export function safeLink(value){return typeof value==='string'&&value.length<2000&&(/^(index|shop|book|blog|posts|post|page)\.html([?#].*)?$/.test(value)||/^#[a-zA-Z0-9_-]*$/.test(value)||/^https:\/\/[^\s<>]+$/i.test(value)||/^(tel:\+?[0-9 ()-]+|mailto:[^\s<>@]+@[^\s<>@]+)$/.test(value));}
function collection(data,key,max=2000){assert(Array.isArray(data[key])&&data[key].length<=max,`Invalid ${key} list.`);const ids=new Set();for(const row of data[key]){assert(row&&typeof row==='object'&&!Array.isArray(row),`Invalid ${key} item.`);assert(typeof row.id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(row.id),`Invalid ${key} ID.`);assert(!ids.has(row.id),`Duplicate ${key} ID.`);ids.add(row.id);}return ids;}
export function validateContent(d){
 assert(d&&typeof d==='object'&&!Array.isArray(d)&&d.schemaVersion===1,'Invalid website document.');
 assert(JSON.stringify(d).length<=1800000,'This update is too large. Upload pictures through Photos.');
 const cat=collection(d,'categories',100),prod=collection(d,'products',2000),serv=collection(d,'services',150);
 for(const key of ['banners','blocks','brands','vehicles','menu','content','pages','kits'])collection(d,key,key==='content'?200:2000);
 assert(Array.isArray(d.serviceCategories)&&d.serviceCategories.length<=100,'Invalid service categories.');d.serviceCategories.forEach(c=>text(c,'Service category',100,true));
 const uniqueCategories=new Set();for(const c of d.categories){text(c.name,'Category name',100,true);const n=c.name.toLowerCase();assert(!uniqueCategories.has(n),'Two categories have the same name.');uniqueCategories.add(n);assert(Array.isArray(c.children)&&c.children.length<=100,'Invalid subcategories.');c.children.forEach(s=>text(s,'Subcategory',100,true));}
 for(const p of d.products){text(p.name,'Product name',150,true);assert(cat.has(p.category),'Choose an existing product category.');assert(Number.isSafeInteger(p.price)&&p.price>0&&p.price<=100000000,'Regular price must be a positive whole BDT amount.');assert(p.sale===null||p.sale===''||Number.isSafeInteger(p.sale)&&p.sale>0&&p.sale<p.price,'Sale price must be lower than regular price.');assert(imageRef(p.image),'Choose a valid product picture.');assert(['In stock','Out of stock','Ask us'].includes(p.stock),'Choose an availability.');text(p.description||'','Product description');text(p.brand||'','Brand',100);assert(!p.subcategory||d.categories.find(c=>c.id===p.category).children.includes(p.subcategory),'Choose a subcategory inside the selected category.');if(p.gallery){assert(Array.isArray(p.gallery)&&p.gallery.length<=10&&p.gallery.every(x=>imageRef(x)),'Invalid product gallery.');}}
 const vehicleIds=new Set(d.vehicles.map(v=>v.id));
 for(const p of d.products){
  assert(['Ask us to confirm','Universal','Selected vehicles'].includes(p.fitment||'Ask us to confirm'),'Choose a vehicle compatibility method.');
  assert(!p.vehicleIds||Array.isArray(p.vehicleIds)&&p.vehicleIds.every(id=>vehicleIds.has(id)),'Choose existing compatible vehicles.');
  assert(p.fitment!=='Selected vehicles'||p.vehicleIds?.length>0,'Select at least one compatible model.');
  assert(!p.vehicleTypes||Array.isArray(p.vehicleTypes)&&p.vehicleTypes.every(t=>['bike','car'].includes(t)),'Choose bike or car compatibility.');
  assert(p.fitment!=='Universal'||p.vehicleTypes?.length>0,'Choose whether the universal product is for bikes, cars or both.');
  if(p.colors){collection({colors:p.colors},'colors',50);const names=new Set();for(const c of p.colors){text(c.name,'Colour name',60,true);assert(!names.has(c.name.toLowerCase()),'Each colour needs a different name.');names.add(c.name.toLowerCase());assert(/^#[0-9a-f]{6}$/i.test(c.hex),'Choose a valid colour swatch.');assert(['In stock','Out of stock'].includes(c.stock),'Choose colour availability.');assert(imageRef(c.image,true),'Choose a valid colour photo.');}}
 }
 d.posts ||= [];collection(d,'posts',500); const targets=new Set([...cat,'Services','Contact','Home','Posts',...d.pages.map(p=>'page:'+p.id),...d.posts.map(p=>'post:'+p.id)]);
 for(const b of d.banners){text(b.name,'Banner name',150,true);text(b.alt,'Picture description',300,true);assert(imageRef(b.image)&&imageRef(b.mobileImage,true),'Choose a valid banner picture.');assert(targets.has(b.destination),'Choose a banner destination.');}
 for(const s of d.services){text(s.name,'Service name',150,true);text(s.description||'','Service description');assert(imageRef(s.image),'Choose a service icon.');assert(['Quote after inspection','Fixed price'].includes(s.mode),'Choose a pricing method.');assert(s.mode!=='Fixed price'||Number.isSafeInteger(Number(s.price))&&Number(s.price)>0,'Enter a whole BDT service price.');}
 for(const b of d.blocks){text(b.name,'Block name',150,true);assert(imageRef(b.image),'Choose a block picture.');assert(['service','category'].includes(b.kind),'Choose a block type.');assert(b.kind==='service'?serv.has(b.target):cat.has(b.target),'Choose a valid block destination.');}
 for(const m of d.menu){text(m.name,'Menu name',100,true);assert(targets.has(m.target),'Choose a valid menu destination.');}
 for(const b of d.brands){text(b.name,'Brand name',100,true);assert(imageRef(b.image),'Choose a brand logo.');}
 for(const k of d.kits){text(k.name,'Bundle name',150,true);assert(Array.isArray(k.productIds)&&k.productIds.length<=20&&k.productIds.every(id=>prod.has(id)),'Choose existing products for each bundle.');}
 for(const c of d.content){text(c.name,'Section name',150,true);assert(['index','shop','book'].includes(c.page),'Invalid page.');assert(Array.isArray(c.fields)&&c.fields.length<200,'Invalid section fields.');for(const f of c.fields){assert(/^[a-zA-Z0-9_-]{1,100}$/.test(f.id),'Invalid field ID.');assert(['text','image','link'].includes(f.kind),'Invalid field type.');text(f.value,'Page content',10000);if(f.kind==='link')assert(safeLink(f.value),'Use a valid website destination or an https link.');if(f.kind==='image')assert(imageRef(f.value),'Choose a valid section picture.');}}
 const slugs=new Set();for(const p of [...d.pages.filter(p=>p.custom),...d.posts]){assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)&&p.slug.length<=100,'Use an address with lowercase letters, numbers and hyphens.');assert(!slugs.has(p.slug),'Each page or post needs a unique address.');slugs.add(p.slug);text(p.title||p.name,'Page title',200,true);if(p.custom){text(p.html||'','Page HTML',100000);text(p.css||'','Page CSS',50000);}else{text(p.body||'','Post body',50000,true);text(p.excerpt||'','Post introduction',1000);assert(imageRef(p.image),'Choose a post cover picture.');text(p.author||'','Author',100);assert(/^\d{4}-\d{2}-\d{2}$/.test(p.date),'Choose a post date.');}}
 for(const p of d.pages){text(p.title,'Page title',200,true);text(p.description,'Search description',500);assert(imageRef(p.shareImage)||p.shareImage.startsWith('https://ahmedmasum2000000.github.io/moto/assets/'),'Choose a valid sharing picture.');}
 for(const v of d.vehicles){assert(['bike','car'].includes(v.type),'Choose bike or car.');text(v.brand,'Vehicle brand',100,true);text(v.name,'Vehicle model',150,true);}
 const s=d.settings;assert(s&&typeof s==='object','Store settings required.');['name','slogan','phone','whatsapp','email','address','hours'].forEach(k=>text(s[k]||'',k,500,k==='name'));assert(imageRef(s.logo)&&imageRef(s.favicon),'Choose a logo and browser icon.');assert(safeLink(s.facebook)&&safeLink(s.map),'Use valid social and map links.');
 return d;
}
export function publicDocument(d){const p=structuredClone(d);p.posts||=[];delete p.photos;const cats=new Set(p.categories.filter(x=>x.visible!==false).map(x=>x.id));p.categories=p.categories.filter(x=>cats.has(x.id));p.products=p.products.filter(x=>x.visible!==false&&cats.has(x.category));p.services=p.services.filter(x=>x.visible!==false);const serviceIds=new Set(p.services.map(x=>x.id)),productIds=new Set(p.products.map(x=>x.id));p.blocks=p.blocks.filter(x=>x.visible!==false&&(x.kind==='service'?serviceIds.has(x.target):cats.has(x.target)));for(const key of ['banners','brands','vehicles','menu','content','pages','posts'])p[key]=p[key].filter(x=>x.visible!==false);const validTarget=t=>cats.has(t)||['Services','Home','Contact','Posts'].includes(t)||p.pages.some(x=>'page:'+x.id===t)||p.posts.some(x=>'post:'+x.id===t);p.menu=p.menu.filter(x=>validTarget(x.target));p.banners=p.banners.filter(x=>validTarget(x.destination));p.kits=p.kits.filter(x=>x.visible!==false&&x.productIds.every(id=>productIds.has(id)));return p;}
export function mediaReferences(value,refs=new Set()){if(typeof value==='string'&&value.startsWith('media:'))refs.add(value.slice(6));else if(Array.isArray(value))value.forEach(v=>mediaReferences(v,refs));else if(value&&typeof value==='object')Object.values(value).forEach(v=>mediaReferences(v,refs));return refs;}
export function resolveMedia(value,urls){if(typeof value==='string'&&value.startsWith('media:')){assert(urls[value.slice(6)],'A picture could not be published.');return urls[value.slice(6)];}if(Array.isArray(value))return value.map(v=>resolveMedia(v,urls));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,resolveMedia(v,urls)]));return value;}
export function validateRequest(b,live){assert(b&&UUID.test(b.key),'Refresh the page and try again.');const name=text(b.name,'Your name',120,true),phone=text(b.phone,'Phone number',30,true).replace(/[\s()-]/g,'');assert(/^\+?[0-9]{8,15}$/.test(phone),'Enter a valid phone number.');assert(['order','booking'].includes(b.kind),'Choose a request type.');assert(!b.website,'Unable to submit request.');let details={notes:text(b.notes||'','Notes',2000),vehicle:text(b.vehicle||'','Vehicle',150),currency:'BDT'};
 if(b.kind==='order'){assert(Array.isArray(b.items)&&b.items.length>0&&b.items.length<=50,'Choose at least one product.');const ids=new Set();details.items=b.items.map(it=>{const key=it.id+'::'+(it.colorId||'');assert(!ids.has(key),'Duplicate product and colour.');ids.add(key);const p=live.products.find(p=>p.id===it.id&&p.visible!==false);assert(p&&p.stock!=='Out of stock','One of the products is unavailable. Please refresh your cart.');assert(Number.isInteger(it.qty)&&it.qty>=1&&it.qty<=50,'Choose a quantity from 1 to 50.');const color=p.colors?.find(c=>c.id===it.colorId&&c.stock!=='Out of stock');assert(!p.colors?.length||color,'Choose an available product colour.');assert(p.colors?.length||!it.colorId,'This product has no colour options.');return {id:p.id,name:p.name,colorId:color?.id||'',colorName:color?.name||'',quantity:it.qty,unitPriceMinor:Math.round((p.sale||p.price)*100)};});details.totalMinor=details.items.reduce((n,i)=>n+i.unitPriceMinor*i.quantity,0);assert(b.expectedTotalMinor===details.totalMinor,'Prices changed. Refresh the cart and review the current total.');}
 else {assert(Array.isArray(b.services)&&b.services.length>0&&b.services.length<=12,'Choose at least one service.');details.services=[...new Set(b.services)].map(id=>{const s=live.services.find(s=>s.id===id&&s.visible!==false&&s.booking!==false);assert(s,'One of the services is unavailable.');return {id:s.id,name:s.name};});details.date=text(b.date||'','Preferred date',10);if(details.date){assert(/^\d{4}-\d{2}-\d{2}$/.test(details.date)&&!Number.isNaN(Date.parse(details.date))&&new Date(details.date).toISOString().slice(0,10)===details.date,'Choose a valid date.');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());assert(details.date>=today,'Choose today or a later date.');}details.slot=text(b.slot||'Any time','Preferred time',100);}
 return {kind:b.kind,name,phone,details};
}
