import {findVehicles,fitsVehicle} from './catalog.mjs';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function catalogFinder(content){
 const root=$('[data-model-search]');if(!root)return;
 const q=$('#model-search',root),list=$('#model-results',root),status=$('[data-model-status]',root),clear=$('[data-model-clear]',root);
 let type='bike',vehicle=null,matches=[],active=-1,category=new URLSearchParams(location.search).get('cat')||'all',subcategory=new URLSearchParams(location.search).get('sub')||'',color='';
 const query=new URLSearchParams(location.search),chosen=query.get('vehicle');
 if(chosen)vehicle=content.vehicles.find(v=>v.id===chosen)||null;
 if(!vehicle&&!query.has('vehicle'))try{const saved=JSON.parse(localStorage.getItem('mm.vehicle.v1')||'null');vehicle=content.vehicles.find(v=>v.id===saved?.id||v.type===saved?.type&&v.brand===saved?.brand&&v.name===saved?.model)||null;}catch{}
 if(vehicle){type=vehicle.type;q.value=vehicle.brand+' '+vehicle.name;}
 const chips=$('[data-filter]')?.parentElement;let sub;
 if(chips){chips.innerHTML=[{id:'all',name:'Everything'},...content.categories].map(c=>`<button class="chip" type="button" data-cms-filter="${esc(c.id)}" aria-pressed="false">${esc(c.name)}</button>`).join('');sub=document.createElement('select');sub.id='cms-subcategory';sub.className='cms-subcategory';sub.setAttribute('aria-label','Product subcategory');chips.parentElement.append(sub);const colours=[...new Set(content.products.flatMap(p=>(p.colors||[]).map(c=>c.name)))].sort();const colour=document.createElement('select');colour.id='catalog-colour';colour.className='cms-subcategory';colour.setAttribute('aria-label','Filter by part colour');colour.innerHTML='<option value="">All colours</option>'+colours.map(c=>`<option>${esc(c)}</option>`).join('');colour.hidden=!colours.length;chips.parentElement.append(colour);colour.addEventListener('change',()=>{color=colour.value;apply();});chips.addEventListener('click',e=>{const b=e.target.closest('[data-cms-filter]');if(b){category=b.dataset.cmsFilter;subcategory='';apply();}});sub.addEventListener('change',()=>{subcategory=sub.value;apply();});}
 function apply(){
  const cat=content.categories.find(c=>c.id===category);if(!cat&&category!=='all')category='all';
  if(sub){sub.innerHTML='<option value="">All subcategories</option>'+(cat?.children||[]).map(n=>`<option ${n===subcategory?'selected':''}>${esc(n)}</option>`).join('');sub.hidden=!cat?.children.length;}
  const matched=content.products.filter(p=>(category==='all'||p.category===category)&&(!subcategory||p.subcategory===subcategory)&&(!color||p.colors?.some(c=>c.name===color&&c.stock!=='Out of stock'))&&fitsVehicle(p,vehicle));const ids=new Set(matched.map(p=>p.id));
  $$('.card[data-product-id]').forEach(el=>el.hidden=!ids.has(el.dataset.productId));
  $$('[data-band]').forEach(b=>b.hidden=!$$('.card:not([hidden])',b).length);
  $$('.kit').forEach((el,i)=>{const kit=content.kits[i];el.hidden=!!vehicle&&(!kit||!kit.productIds.every(id=>fitsVehicle(content.products.find(p=>p.id===id),vehicle)));});
  const kits=$('.kits');if(kits)kits.hidden=!$$('.kit:not([hidden])',kits).length;
  $$('[data-cms-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cmsFilter===category)));$$('[data-result-count]').forEach(el=>el.textContent=matched.length);
  const empty=$('[data-catalog-empty]');if(empty){empty.hidden=matched.length>0;empty.innerHTML=vehicle?`<h3 class="h-2">No confirmed matches yet.</h3><p class="lede">We haven’t listed a compatible product for ${esc(vehicle.brand+' '+vehicle.name)} in this selection. Try another category or ask our team to check the fit.</p><a class="btn btn--red" href="https://wa.me/${content.settings.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent('Please help me find parts for '+vehicle.brand+' '+vehicle.name)}" target="_blank" rel="noopener">Ask about this model ↗</a>`:'<h3 class="h-2">No products in this selection.</h3><p class="lede">Try another category or colour.</p>';}
  status.textContent=vehicle?`${matched.length} compatible ${matched.length===1?'product':'products'} for ${vehicle.brand} ${vehicle.name}`:'Type a model. Choose your ride. Find the right products.';
  clear.hidden=!vehicle;q.setAttribute('aria-label',`Search ${type==='bike'?'bike':'car'} model`);q.placeholder=type==='bike'?'Search bike model · R15, Gixxer, Pulsar…':'Search car model · Corolla, Civic, Vezel…';
  $$('[data-model-type]',root).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.modelType===type)));
  const u=new URL(location.href);if(category==='all')u.searchParams.delete('cat');else u.searchParams.set('cat',category);if(subcategory)u.searchParams.set('sub',subcategory);else u.searchParams.delete('sub');if(vehicle)u.searchParams.set('vehicle',vehicle.id);else u.searchParams.delete('vehicle');history.replaceState(null,'',u);window.dispatchEvent(new Event('mm:urlchange'));
 }
 function suggestions(){matches=findVehicles(content.vehicles,q.value,type);active=-1;list.innerHTML=matches.map((v,i)=>`<button type="button" role="option" tabindex="-1" id="model-option-${i}" data-model-id="${esc(v.id)}" aria-selected="false"><span>${esc(v.brand)} <strong>${esc(v.name)}</strong></span><span>View products →</span></button>`).join('')||'<p>No model found. Try the model name or manufacturer.</p>';list.hidden=false;q.setAttribute('aria-expanded','true');q.removeAttribute('aria-activedescendant');}
 function close(){list.hidden=true;q.setAttribute('aria-expanded','false');q.removeAttribute('aria-activedescendant');}
 function choose(id){vehicle=content.vehicles.find(v=>v.id===id);if(!vehicle)return;type=vehicle.type;q.value=vehicle.brand+' '+vehicle.name;try{localStorage.setItem('mm.vehicle.v1',JSON.stringify({id:vehicle.id,type,brand:vehicle.brand,model:vehicle.name}));}catch{}close();apply();q.focus();}
 q.addEventListener('input',()=>{if(vehicle){vehicle=null;try{localStorage.removeItem('mm.vehicle.v1');}catch{}apply();}suggestions();});q.addEventListener('focus',()=>{if(!vehicle)suggestions();});
 q.addEventListener('keydown',e=>{if(e.key==='Escape'){close();return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(list.hidden)suggestions();if(!matches.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length;$$('[role=option]',list).forEach((b,i)=>{b.setAttribute('aria-selected',String(i===active));if(i===active)b.scrollIntoView({block:'nearest'});});q.setAttribute('aria-activedescendant','model-option-'+active);}if(e.key==='Enter'){e.preventDefault();if(matches.length&&!list.hidden)choose(matches[Math.max(0,active)].id);}});
 root.addEventListener('click',e=>{const option=e.target.closest('[data-model-id]');if(option)choose(option.dataset.modelId);const toggle=e.target.closest('[data-model-type]');if(toggle){type=toggle.dataset.modelType;vehicle=null;q.value='';try{localStorage.removeItem('mm.vehicle.v1');}catch{}apply();q.focus();suggestions();}if(e.target.closest('[data-model-clear]')){vehicle=null;q.value='';try{localStorage.removeItem('mm.vehicle.v1');}catch{}apply();q.focus();suggestions();}});
 document.addEventListener('pointerdown',e=>{if(!root.contains(e.target))close();});apply();
}
