import {catalogFinder} from './finder.js';
import {homeBackground} from './home-hero.js';
const finderStyles=document.createElement('link');finderStyles.rel='stylesheet';finderStyles.href='cms/finder.css';document.head.append(finderStyles);
import {cartLine} from './catalog.mjs';
import {live,admin,request,watchLive} from './backend.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
const query=new URLSearchParams(location.search),draft=query.get('preview')==='draft';
let content,revision,mediaUrls={};
const img=ref=>ref?.startsWith('media:')?mediaUrls[ref.slice(6)]||'':ref||'';
const catName=id=>content.categories.find(c=>c.id===id)?.name||id;
function path(target){if(target==='Home')return 'index.html';if(target==='Contact')return 'index.html#contact';if(target==='Services')return 'book.html';if(target==='Posts')return 'posts.html';if(target.startsWith('page:')){const p=content.pages.find(p=>'page:'+p.id===target);return p?.custom?'page.html?slug='+encodeURIComponent(p.slug):(p?.id||'index')+'.html';}if(target.startsWith('post:'))return 'post.html?slug='+encodeURIComponent(content.posts?.find(p=>'post:'+p.id===target)?.slug||'');return 'shop.html?cat='+encodeURIComponent(target);}
function add(p,label='Add to cart'){if(p.colors?.length)return `<button class="btn btn--red btn--sm" type="button" data-product="${esc(p.id)}">Choose colour →</button>`;return `<button class="btn btn--red btn--sm" type="button" data-add="${esc(p.id)}" data-name="${esc(p.name)}" data-price="${p.sale||p.price}" data-cat="${esc(catName(p.category))}" ${p.stock==='Out of stock'?'disabled':''}>${p.stock==='Out of stock'?'Out of stock':label} →</button>`;}
function card(p){const brand=content.brands.find(b=>b.name.toLowerCase()===p.brand?.toLowerCase());const saving=p.sale?Math.round((1-p.sale/p.price)*100):0;return `<article class="card" data-cat="${esc(p.category)}" data-product-id="${esc(p.id)}" data-sub="${esc(p.subcategory||'')}" data-price="${p.sale||p.price}" data-save="${saving}" data-dealer="${brand?1:0}">${saving?`<span class="badge badge--off">−${saving}%</span>`:''}${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}<button class="card__art cms-product-art" data-product="${esc(p.id)}" aria-label="View ${esc(p.name)}"><img class="cms-product-picture" src="${esc(img(p.image))}" alt="${esc(p.name)}" loading="lazy">${brand?`<img class="card__brand" src="${esc(img(brand.image))}" alt="${esc(brand.name)}">`:''}</button><p class="card__cat">${esc(catName(p.category))}</p><h3 class="card__name"><button data-product="${esc(p.id)}">${esc(p.name)}</button></h3><p class="card__perk">${esc(p.description)}</p>${p.colors?.length?`<div class="cms-colour-swatches" aria-label="Available colours">${p.colors.map(c=>`<button type="button" data-product="${esc(p.id)}" data-selected-color="${esc(c.id)}" style="--swatch:${esc(c.hex)}" aria-label="${esc(c.name)}${c.stock==='Out of stock'?' — out of stock':''}"></button>`).join('')}</div>`:''}<div class="card__row"><div class="card__price">${money(p.sale||p.price)}${p.sale?` <s>${money(p.price)}</s>`:''}</div>${add(p,'Add')}</div></article>`;}
function hydrate(){
 window.MM_CONTENT=content;window.MM_CART_LINE=cartLine;
 // All values enter the DOM as text, attributes, or escaped markup. Custom code is sandboxed below.
 for(const section of content.content||[])for(const f of section.fields){const attr=f.kind==='text'?'text':f.kind==='image'?'image':'link';$$(`[data-cms-${attr}="${CSS.escape(f.id)}"]`).forEach(el=>{if(f.kind==='text')el.textContent=f.value;else el.setAttribute(f.kind==='image'?'src':'href',f.kind==='image'?img(f.value):f.value);});}
 const known=new Set((content.content||[]).map(s=>s.id));$$('[data-cms-section]').forEach(el=>{if(!known.has(el.dataset.cmsSection)&&el.querySelector('[data-cms-text],[data-cms-image],[data-cms-link]'))el.hidden=true;});
 // Only reorder sections amongst the existing CMS slots in the same parent.
 const parents=new Set($$('[data-cms-section]').map(el=>el.parentElement));for(const parent of parents){const children=[...parent.children].filter(el=>known.has(el.dataset.cmsSection));if(children.length<2)continue;const placeholders=children.map(el=>{const mark=document.createComment('cms section');el.replaceWith(mark);return mark;});children.sort((a,b)=>content.content.findIndex(s=>s.id===a.dataset.cmsSection)-content.content.findIndex(s=>s.id===b.dataset.cmsSection));placeholders.forEach((mark,i)=>mark.replaceWith(children[i]));}
 const s=content.settings;$$('img[src*="assets/logo."]').forEach(el=>{el.src=img(s.logo);el.alt=s.name;});const fav=$('link[rel="icon"]');if(fav)fav.href=img(s.favicon);
 $$('a[href^="tel:"]').forEach(a=>{a.href='tel:'+s.phone.replace(/\s/g,'');a.textContent=s.phone;});$$('a[href^="mailto:"]').forEach(a=>{a.href='mailto:'+s.email;if(a.textContent.includes('@'))a.textContent=s.email;});$$('a[href*="wa.me/"]').forEach(a=>a.href='https://wa.me/'+s.whatsapp.replace(/\D/g,''));$$('a[href*="facebook.com"]').forEach(a=>a.href=s.facebook);$$('a[href*="maps.google"],a[href*="google.com/maps"]').forEach(a=>a.href=s.map);
 const menuItem=(m,mobile=false)=>{const category=content.categories.find(c=>c.id===m.target);const children=m.target==='Services'?content.serviceCategories.map(n=>({name:n,url:'book.html?category='+encodeURIComponent(n)})):(category?.children||[]).map(n=>({name:n,url:path(m.target)+'&sub='+encodeURIComponent(n)}));return `<div class="cms-nav-item"><a class="${mobile?'menu__link':'nav__link'}" href="${esc(path(m.target))}">${esc(m.name)}</a>${children.length?`<button class="cms-sub-toggle" aria-label="Show ${esc(m.name)} categories" aria-expanded="false">⌄</button><div class="cms-submenu">${children.map(c=>`<a href="${esc(c.url)}">${esc(c.name)}</a>`).join('')}</div>`:''}</div>`;};
 const nav=$('.nav__menu');if(nav)nav.innerHTML=content.menu.map(m=>menuItem(m)).join('');const mobile=$('.menu__panel');if(mobile){const top=$('.menu__top',mobile)?.outerHTML||'';mobile.innerHTML=top+content.menu.map(m=>menuItem(m,true)).join('')+`<a class="btn btn--red" href="book.html">Book a service →</a><div class="menu__foot"><p>${esc(s.address)}</p><a href="tel:${esc(s.phone)}">${esc(s.phone)}</a></div>`;}
 const carousel=$('.hero-slider .carousel__track');if(carousel){carousel.innerHTML=content.banners.map((b,i)=>`<a class="slide" href="${esc(path(b.destination))}"><picture>${b.mobileImage?`<source media="(max-width:600px)" srcset="${esc(img(b.mobileImage))}">`:''}<img src="${esc(img(b.image))}" alt="${esc(b.alt)}" width="1920" height="960" style="object-position:${Number(b.focalX??50)}% ${Number(b.focalY??50)}%" loading="${i?'lazy':'eager'}"></picture></a>`).join('');if(!content.banners.length)$('.hero-slider').hidden=true;}
 const grid=$('[data-grid]');if(grid)grid.innerHTML=content.products.map(card).join('');
 const bands=$$('[data-band]');const template=bands.find(b=>b.dataset.band!=='deals');if(template)for(const cat of content.categories){if(!bands.some(b=>b.dataset.band===cat.id)){const band=template.cloneNode(true);band.dataset.band=cat.id;band.id='cat-'+cat.id;template.parentElement.append(band);bands.push(band);}}
 for(const band of bands){const category=content.categories.find(c=>c.id===band.dataset.band),deals=band.dataset.band==='deals';const list=content.products.filter(p=>deals?!!p.sale:p.category===band.dataset.band);if(!deals&&!category){band.remove();continue;}$('.carousel__track',band).innerHTML=list.map(card).join('');if(category){$('.band__title',band).textContent=category.name;const info=$('.band__sub',band);if(info&&category.description)info.textContent=category.description;}const count=$('.band__head > .label',band);if(count)count.textContent=list.length+(deals?' on offer':' items');}

 const kits=$('.kits__grid');if(kits)kits.innerHTML=content.kits.map(k=>{const products=k.productIds.map(id=>content.products.find(p=>p.id===id)).filter(Boolean),items=products.map(p=>({id:p.id,name:p.name,cat:catName(p.category),price:p.sale||p.price}));return `<article class="kit"><p class="label label--red">${items.length} items · one visit</p><h3 class="kit__title">${esc(k.name)}</h3><p class="kit__sub">${esc(k.description)}</p><ul class="kit__list">${items.map(p=>`<li><span>${esc(p.name)}</span><b>${money(p.price)}</b></li>`).join('')}</ul><div class="kit__foot"><p class="kit__total"><small>Bundle total</small>${money(items.reduce((a,p)=>a+p.price,0))}</p><button class="btn btn--red btn--sm" data-kit="${esc(JSON.stringify(items))}" ${products.some(p=>p.stock==='Out of stock')?'disabled':''}>Add all ${items.length}</button></div></article>`;}).join('');
 for(const button of $$('[data-kit]')){let items=JSON.parse(button.dataset.kit);const variants=items.filter(i=>content.products.find(p=>p.id===i.id)?.colors?.length);if(!variants.length)continue;button.disabled=true;const root=button.closest('.kit');for(const item of variants){const p=content.products.find(p=>p.id===item.id);const label=document.createElement('label');label.className='cms-kit-colour';label.innerHTML=esc(p.name)+' · colour<select data-kit-colour="'+esc(p.id)+'"><option value="">Choose colour</option>'+p.colors.filter(c=>c.stock!=='Out of stock').map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select>';root.insertBefore(label,$('.kit__foot',root));}root.addEventListener('change',()=>{const selections=$$('[data-kit-colour]',root);button.disabled=selections.some(s=>!s.value)||items.some(i=>content.products.find(p=>p.id===i.id)?.stock==='Out of stock');button.dataset.kit=JSON.stringify(items.map(i=>{const c=content.products.find(p=>p.id===i.id)?.colors?.find(c=>c.id===selections.find(s=>s.dataset.kitColour===i.id)?.value);return {...i,colorId:c?.id||'',colorName:c?.name||'',lineKey:i.id+'::'+(c?.id||'')};}));});}

 $$('.dealer__group .brandmarks').forEach((marks,i)=>{marks.innerHTML=content.brands.filter(b=>b.group===(i===0?'tyres':'oil')).map(b=>`<span><img src="${esc(img(b.image))}" alt="${esc(b.alt||b.name)}" loading="lazy"></span>`).join('');});
 // Other reused logos receive the same published artwork.
 $$('img[src*="assets/brands/"]').forEach(el=>{const brand=content.brands.find(b=>b.name.toLowerCase()===el.alt.toLowerCase());if(brand)el.src=img(brand.image);});
 const svc=$('.svc-grid'),details=$('[data-svc-detail]');if(svc&&details){svc.innerHTML=content.blocks.map((b,i)=>`<button class="svc" type="button" role="tab" id="svctab-${b.id}" aria-controls="svcpanel-${b.id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-svc="${b.id}"><span class="svc__no">${String(i+1).padStart(2,'0')} — ${b.kind==='service'?'Booking':'Shop'}</span><img class="svc__icon" src="${esc(img(b.image))}" alt="" loading="lazy"><h3 class="svc__title">${esc(b.name)}</h3><span class="svc__cta">View details →</span></button>`).join('');details.innerHTML=content.blocks.map((b,i)=>{const s=b.kind==='service'?content.services.find(s=>s.id===b.target):null;return `<article class="svc-panel" role="tabpanel" id="svcpanel-${b.id}" aria-labelledby="svctab-${b.id}" data-panel="${b.id}" ${i?'hidden':''}><div><p class="label label--red">${b.kind==='service'?'WORKSHOP':'SHOP'}</p><h3 class="h-2">${esc(b.name)}</h3><p class="lede">${esc(s?.description||b.description)}</p>${s?`<p class="label">${s.mode==='Fixed price'?money(s.price):'Quote after inspection'} · ${esc(s.duration)}</p>`:''}<ul class="list-plain">${(s?.included||b.included||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul><a class="btn btn--red" href="${b.kind==='service'?'book.html?service='+encodeURIComponent(b.target):path(b.target)}">${esc(b.button||'View details')} →</a></div><div class="svc-panel__art"><img class="svc-panel__icon" src="${esc(img(b.image))}" alt=""></div></article>`;}).join('');}
 const vehicles={bike:{},car:{}};for(const v of content.vehicles)(vehicles[v.type][v.brand]||=[]).push(v.name);const vehicleData=$('#vehicle-data');if(vehicleData)vehicleData.textContent=JSON.stringify(vehicles);
 window.MM_SEARCH=[...content.products.map(p=>({t:p.name,k:catName(p.category),u:'shop.html?cat='+p.category+'&product='+p.id,g:'Shop',p:p.sale||p.price})),...content.services.map(s=>({t:s.name,k:s.description,u:'book.html?service='+s.id,g:'Service'})),...content.pages.map(p=>({t:p.name,k:p.description,u:path('page:'+p.id),g:'Page'})),...(content.posts||[]).map(p=>({t:p.name,k:p.excerpt,u:path('post:'+p.id),g:'Post'}))];
 const pageId=(location.pathname.split('/').pop()||'index.html').replace('.html','');const page=content.pages.find(p=>p.id===pageId);if(page)metadata(page.title,page.description,img(page.shareImage));
 homeBackground($('.home-hero'),content.banners,img);
 catalogFinder(content);publicPages();booking();cartRequest();
 if(draft){const notice=document.createElement('div');notice.className='cms-preview-notice';notice.textContent='PRIVATE DRAFT PREVIEW · Only signed-in staff can view this version';document.body.prepend(notice);$$('a[href]').forEach(a=>{const u=new URL(a.href);if(u.origin===location.origin&&/\.html$/.test(u.pathname)){u.searchParams.set('preview','draft');a.href=u.href;}});}
}
function metadata(title,description,image){document.title=title;for(const [key,value] of [['description',description],['og:title',title],['og:description',description],['og:image',image]]){let el=$(`meta[${key.startsWith('og:')?'property':'name'}="${key}"]`);if(!el){el=document.createElement('meta');el.setAttribute(key.startsWith('og:')?'property':'name',key);document.head.append(el);}el.content=value||'';}}
function publicPages(){const root=$('#cms-page');if(!root)return;const slug=query.get('slug');const type=root.dataset.type;if(type==='pages'){const page=content.pages.find(p=>p.custom&&p.slug===slug);if(!page){root.innerHTML='<section class="section"><h1 class="h-1">Page not found.</h1><a class="btn" href="index.html">Return home →</a></section>';return;}metadata(page.title,page.description,img(page.shareImage));const frame=document.createElement('iframe');frame.title=page.title;frame.className='cms-code-page';frame.setAttribute('sandbox','');frame.setAttribute('referrerpolicy','no-referrer');const base=new URL('./',location.href).href;const csp="default-src 'none'; img-src https: data:; style-src 'unsafe-inline' https: http://127.0.0.1:8781; font-src https: http://127.0.0.1:8781; script-src 'none'; form-action 'none'; base-uri 'none'";frame.srcdoc=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="${csp}"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${esc(base)}styles.css"><style>body{margin:0;overflow:auto}*{border-radius:0!important}h1,h2,h3{font-family:Archivo,Inter,sans-serif}h1{font-size:clamp(40px,8vw,90px)}.section{padding:40px max(24px,5vw)}${page.css.replace(/<\/style/gi,'<\\/style')}</style></head><body>${page.html}</body></html>`;root.replaceChildren(frame);return;}
 const postCard=p=>`<a class="cms-post-card" href="post.html?slug=${encodeURIComponent(p.slug)}"><img src="${esc(img(p.image))}" alt="" loading="lazy"><p class="label label--red">${esc(p.date)} · ${esc(p.author)}</p><h2 class="h-2">${esc(p.name)}</h2><p class="lede">${esc(p.excerpt)}</p><span class="label">Read story →</span></a>`;
 if(type==='posts'){root.innerHTML=`<section class="section"><p class="label label--red">THE MOTO JOURNAL</p><h1 class="h-1">From the workshop.</h1><div class="cms-post-grid">${(content.posts||[]).map(postCard).join('')||'<p class="lede">New stories are on the way.</p>'}</div></section>`;return;}
 const p=content.posts?.find(p=>p.slug===slug);if(!p){root.innerHTML='<section class="section"><h1 class="h-1">Post not found.</h1><a href="posts.html">All posts →</a></section>';return;}metadata(p.name+' · '+content.settings.name,p.excerpt,img(p.image));const body=p.body.split(/\n\s*\n/).map(block=>{if(block.startsWith('## '))return '<h2>'+esc(block.slice(3))+'</h2>';if(block.split('\n').every(l=>l.startsWith('- ')))return '<ul>'+block.split('\n').map(l=>'<li>'+esc(l.slice(2))+'</li>').join('')+'</ul>';return '<p>'+esc(block).replace(/\n/g,'<br>')+'</p>';}).join('');root.innerHTML=`<article class="section cms-post"><a class="label" href="posts.html">← All stories</a><p class="label label--red">${esc(p.date)} · ${esc(p.author)}</p><h1 class="h-1">${esc(p.name)}</h1><p class="lede">${esc(p.excerpt)}</p><img class="cms-post-cover" src="${esc(img(p.image))}" alt="${esc(p.name)}"><div class="cms-post-body">${body}</div></article>`;}
function booking(){const form=$('[data-booking]');if(!form)return;form.removeAttribute('data-booking');form.removeAttribute('novalidate');$('.picks',form).innerHTML=content.services.filter(s=>s.booking!==false).map(s=>`<label class="pick"><input type="checkbox" name="service" value="${esc(s.id)}" ${(query.get('service')||'').toLowerCase()===s.id.toLowerCase()||query.get('category')===s.category?'checked':''}><span>${esc(s.name)}${s.mode==='Fixed price'?' · '+money(s.price):''}</span></label>`).join('');$('button[type=submit]',form).textContent='Send booking request →';const out=$('[data-booking-out]',form);out.hidden=false;out.innerHTML='<p class="cms-request-note">Sending a request does not reserve a slot. Our team will call to confirm.</p><p class="cms-form-status" role="status"></p>';const date=$('[name=date]',form);if(date)date.min=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());try{const v=JSON.parse(localStorage.getItem('mm.vehicle.v1'));$('[name=vehicle]',form).value=query.get('vehicle')||(v?v.brand+' '+v.model:'');}catch{}let key=crypto.randomUUID();form.addEventListener('submit',async e=>{e.preventDefault();const button=$('button[type=submit]',form),status=$('.cms-form-status',form),f=new FormData(form);if(draft){status.textContent='This is a draft preview. Open the published website to send a request.';return;}button.disabled=true;status.textContent='Sending your request…';try{const result=await request({key,kind:'booking',name:f.get('name'),phone:f.get('phone'),vehicle:f.get('vehicle'),services:f.getAll('service'),date:f.get('date'),slot:f.get('slot'),notes:f.get('notes'),website:''});status.textContent=result.message+' Your reference: '+result.receipt;form.reset();key=crypto.randomUUID();}catch(err){status.textContent=err.message;}finally{button.disabled=false;}});}
function cartRequest(){const foot=$('.drawer__foot');if(!foot)return;const form=document.createElement('form');form.className='cms-order-form';form.innerHTML='<h3>Send a product request</h3><label for="order-name">Your name</label><input id="order-name" name="name" autocomplete="name" required maxlength="120"><label for="order-phone">Phone number</label><input id="order-phone" name="phone" type="tel" autocomplete="tel" required maxlength="30"><button class="btn btn--red btn--block">Send request →</button><p class="cms-form-status" role="status">We confirm stock and price before you pay.</p>';foot.prepend(form);const wa=$('[data-cart-wa]');if(wa){wa.classList.remove('btn--red');wa.textContent='Or ask on WhatsApp ↗';}let key=crypto.randomUUID();form.addEventListener('submit',async e=>{e.preventDefault();const button=$('button',form),status=$('[role=status]',form);if(draft){status.textContent='Requests are disabled in a draft preview.';return;}button.disabled=true;try{const cart=JSON.parse(localStorage.getItem('mm.cart.v1')||'[]'),f=new FormData(form);const result=await request({key,kind:'order',name:f.get('name'),phone:f.get('phone'),items:cart.map(i=>({id:i.id,qty:i.qty,colorId:i.colorId||''})),expectedTotalMinor:cart.reduce((sum,i)=>sum+i.price*i.qty*100,0),website:''});status.textContent=result.message+' Reference: '+result.receipt;key=crypto.randomUUID();}catch(err){status.textContent=err.message;}finally{button.disabled=false;}});}
function productDetails(id,colorId=''){const p=content.products.find(p=>p.id===id);if(!p)return;let dialog=$('#cms-product-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='cms-product-dialog';dialog.className='cms-product-dialog';dialog.setAttribute('aria-labelledby','cms-product-title');document.body.append(dialog);}dialog.innerHTML=`<button class="cms-dialog-close" aria-label="Close product details">Close ✕</button><div class="cms-product-details"><div><img class="cms-detail-image" src="${esc(img(p.image))}" alt="${esc(p.name)}"><div class="cms-gallery">${[p.image,...p.gallery||[]].map(ref=>`<button data-gallery="${esc(img(ref))}" aria-label="Show product photo"><img src="${esc(img(ref))}" alt=""></button>`).join('')}</div></div><div><p class="label label--red">${esc(catName(p.category))} · ${esc(p.stock)}</p><h2 id="cms-product-title">${esc(p.name)}</h2><p class="lede">${esc(p.description)}</p><p class="card__price">${money(p.sale||p.price)} ${p.sale?'<s>'+money(p.price)+'</s>':''}</p><p>${esc(p.specifications||'')}</p><p class="label">${p.fitment==='Universal'?'Universal fit — confirm with our team':p.fitment==='Selected vehicles'?(content.vehicles.filter(v=>p.vehicleIds?.includes(v.id)).map(v=>v.brand+' '+v.name).join(', ')||'Ask us to confirm fitment'):'Ask us to confirm fitment'}</p>${p.colors?.length?`<fieldset class="cms-colour-options"><legend>Choose your colour</legend>${p.colors.map(c=>`<button type="button" data-choose-colour="${esc(c.id)}" style="--swatch:${esc(c.hex)}" aria-pressed="false" ${c.stock==='Out of stock'?'disabled':''}><i></i>${esc(c.name)}${c.stock==='Out of stock'?' · Out of stock':''}</button>`).join('')}</fieldset><p class="cms-colour-status" role="status">Choose a colour to add this item.</p><button type="button" class="btn btn--red" data-colour-add disabled>Add to cart →</button>`:add(p)}</div></div>`;$('.cms-dialog-close',dialog).onclick=()=>dialog.close();dialog.showModal();const chooseColor=id=>{const c=p.colors?.find(c=>c.id===id&&c.stock!=='Out of stock');if(!c)return;$$('[data-choose-colour]',dialog).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.chooseColour===id)));$('.cms-detail-image',dialog).src=img(c.image||p.image);$('.cms-colour-status',dialog).textContent='Selected: '+c.name;const b=$('[data-colour-add]',dialog);b.dataset.add=p.id;b.dataset.colorId=c.id;b.dataset.colorName=c.name;b.dataset.name=p.name;b.dataset.cat=catName(p.category);b.dataset.price=p.sale||p.price;b.disabled=p.stock==='Out of stock';};if(colorId)chooseColor(colorId);dialog.onclick=e=>{const c=e.target.closest('[data-choose-colour]');if(c)chooseColor(c.dataset.chooseColour);const b=e.target.closest('[data-gallery]');if(b)$('.cms-detail-image',dialog).src=b.dataset.gallery;const a=e.target.closest('[data-add]');if(a)dialog.close();};}
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]');if(p)productDetails(p.dataset.product,p.dataset.selectedColor);const toggle=e.target.closest('.cms-sub-toggle');if(toggle){const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.parentElement.classList.toggle('cms-expanded',!open);}});
try{if(draft){const r=await admin('load');if(!r.draft)throw new Error('This account cannot preview website drafts.');mediaUrls=r.mediaUrls;content=r.draft.content;revision='draft-'+r.draft.version;const {publicDocument}=await import('../supabase/functions/moto-admin/schema.mjs');content=publicDocument(content);}else{const r=await live();content=r.content;revision=r.revision;}hydrate();document.documentElement.dataset.cmsRevision=revision;}catch(e){const message=document.createElement('div');message.className='cms-preview-notice';message.setAttribute('role','alert');message.textContent=draft?'Sign in to the control room to view this draft.':'Live updates could not be loaded. Refresh before placing a request.';document.body.prepend(message);if(draft){$('main')?.replaceChildren(message.cloneNode(true));}console.error('Moto content could not load:',e.message);}
// Load the existing motion, fitment and shopping interactions after content is in place.
const script=document.createElement('script');script.src='app.js?v=home-hero-2';script.onload=()=>{const id=query.get('product');if(id&&content)productDetails(id);};document.body.append(script);
if(content&&!draft){
 const stop=watchLive(revision,()=>{
  if(document.activeElement?.matches('input,textarea,select')||$$('form input:not([type=checkbox]):not([type=radio]),form textarea').some(el=>el.value&&el.value!==el.defaultValue)){
   if($('#cms-update-notice'))return;
   const notice=document.createElement('div');notice.id='cms-update-notice';notice.className='cms-preview-notice';notice.setAttribute('role','status');notice.innerHTML='The store has been updated. <button type="button">Load the latest version →</button>';
   $('button',notice).onclick=()=>location.reload();document.body.prepend(notice);
  }else location.reload();
 });
 window.addEventListener('pagehide',stop,{once:true});
}
