const fs=require('node:fs');
const cheerio=require('cheerio');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const load=name=>cheerio.load(fs.readFileSync(path.join(root,name),'utf8'));
if(fs.readFileSync(path.join(root,'index.html'),'utf8').includes('data-cms-text'))throw new Error('This one-time migration has already been run. Use the control room for content edits.');
const home=load('index.html'), shop=load('shop.html');
const clean=s=>s.replace(/\s+/g,' ').trim();
const imageFor={oil:'engine-oil',tyres:'tyres',parts:'spare-parts',after:'modifications',helmets:'helmets'};
const categories=[{id:'tyres',name:'TYRE',children:[]},{id:'oil',name:'ENGINE OIL',children:[]},{id:'parts',name:'STOCK PARTS',children:[]},{id:'after',name:'AFTER MARKET PARTS',children:[]},{id:'helmets',name:'Accessories',children:['Fog Light','Windbreaker','Led','Hand Gloves','Rider Jacket','Helmet Accessories','Raincoat','Intercom','Disc Lock','Light','Helmets','Safety Item']}].map(c=>({...c,visible:true,image:'assets/icons/'+imageFor[c.id]+'.png',description:''}));
const brands=fs.readdirSync(path.join(root,'assets/brands')).filter(x=>x.endsWith('.webp')).map(file=>({id:file.replace('.webp',''),name:({'bp':'BP','mrf':'MRF','cst':'CST','ceat':'CEAT','liqui-moly':'Liqui Moly','maxima':'Maxima Pro'}[file.replace('.webp','')]||file.replace('.webp','').replace(/^./,x=>x.toUpperCase())),image:'assets/brands/'+file,group:['mrf','ceat','pirelli','cst','eurogrip'].includes(file.replace('.webp',''))?'tyres':'oil',visible:true}));
const products=[];
shop('[data-grid] .card').each((i,node)=>{const el=shop(node),b=el.find('[data-add]'),selling=Number(b.attr('data-price')),regular=Number(el.find('.card__price s').text().replace(/\D/g,''))||selling,name=clean(el.find('.card__name').text()),category=el.attr('data-cat'),brand=brands.find(x=>name.toLowerCase().startsWith(x.name.toLowerCase().replace(' pro','')));products.push({id:b.attr('data-add'),name,brand:brand?.name||'',category,subcategory:category==='helmets'?(name.includes('Gloves')?'Hand Gloves':'Helmets'):'',price:regular,sale:regular>selling?selling:null,description:clean(el.find('.card__perk').text()),image:'assets/icons/'+imageFor[category]+'.png',gallery:[],stock:'In stock',visible:true,featured:!!el.find('.badge:not(.badge--off)').length,badge:clean(el.find('.badge:not(.badge--off)').first().text()),dealer:el.attr('data-dealer')==='1',specifications:'',fitment:'Ask us to confirm',vehicleIds:[]});});
const banners=[];home('.hero-slider .slide').each((i,n)=>{const el=home(n),img=el.find('img');banners.push({id:'banner-'+i,name:img.attr('alt'),alt:img.attr('alt'),image:img.attr('src'),mobileImage:'',focalX:50,focalY:50,destination:new URL(el.attr('href'),'https://moto.example').searchParams.get('cat')||'after',visible:true});});
const blocks=[];home('.svc-grid .svc').each((i,n)=>{const el=home(n),id=el.attr('data-svc'),panel=home('#svcpanel-'+id),a=panel.find('a.btn').first(),kind=i<4?'service':'category';blocks.push({id,name:clean(el.find('.svc__title').text()),image:el.find('img').attr('src'),description:clean(panel.find('.lede').first().text()),included:panel.find('li').map((_,li)=>clean(home(li).text())).get(),target:id==='oil'?'oil':id==='parts'?'parts':id==='tyres'?'tyres':id==='helmets'?'helmets':id,kind,button:clean(a.text()),visible:true});});
const services=blocks.filter(b=>b.kind==='service').map(b=>({id:b.id,name:b.name,image:b.image,description:b.description,included:b.included,category:b.id==='painting'?'Painting':'Mastet Service',mode:'Quote after inspection',price:null,duration:b.id==='washing'?'Under 1 hour':'Confirmed after inspection',visible:true,booking:true}));
const kits=[];shop('.kit').each((i,n)=>{const el=shop(n),b=el.find('[data-kit]');if(!b.length)return;kits.push({id:'kit-'+i,name:clean(el.find('.kit__title').text()),description:clean(el.find('.kit__sub').text()),productIds:JSON.parse(b.attr('data-kit')).map(x=>x.id),visible:true});});
const vehicleData=JSON.parse(home('#vehicle-data').text());
const vehicles=[];Object.entries(vehicleData).forEach(([type,makers])=>Object.entries(makers).forEach(([brand,models])=>models.forEach((name,i)=>vehicles.push({id:type+'-'+brand.toLowerCase()+'-'+i,type,brand,name,visible:true}))));
const groupNames={fitment:'Welcome & ride finder','cat-deals':'Discounts & offers','cat-oil':'Engine oil introduction','cat-tyres':'Tyres introduction','cat-parts':'Stock parts introduction','cat-after':'Aftermarket introduction','cat-helmets':'Accessories introduction',brands:'Performance brands',dealer:'Official dealer',services:'Services & shop introduction',pricing:'Service packages',process:'How it works',faq:'Questions & answers',contact:'Contact details'};
const content=[],pages=[];
for(const file of ['index.html','shop.html','book.html']){
 const $=load(file),page=file.replace('.html','');pages.push({id:page,name:page==='index'?'Home':page==='shop'?'Shop':'Booking',title:$('title').text(),description:$('meta[name="description"]').attr('content')||'',shareImage:$('meta[property="og:image"]').attr('content')||'assets/banners/frando-brakes.webp'});
 let groupIndex=0,fieldIndex=0;
 const managed='.card,.kit,.svc-grid,.svc-detail,.nav__menu,.menu__panel,.hero-slider,.dealer-logos,.brand-strip,.brands-mosaic,.fit,.fit-bar,[data-vehicle-data]';
 const roots=$('main > section,main > div.marquee,main > div:not([class]),footer');
 roots.each((_,node)=>{const el=$(node),id=page+'-'+(el.attr('id')||'section-'+(++groupIndex)),name=groupNames[el.attr('id')]||clean(el.find('h1,h2,h3').first().text()).slice(0,65)||(node.tagName==='footer'?'Footer':'Extra website text');el.attr('data-cms-section',id);const group={id,page,name,visible:true,fields:[],hint:'',order:content.length};
 function visit(parent){for(const node of [...(parent.children||[])]){if(node.type==='text'){const text=clean(node.data||'');if(!text||/^\d+$/.test(text)||/^[→↗+−✕✓]+$/.test(text))continue;const par=$(node.parent);if(par.closest(managed).length||par.closest('script,style,svg,pre,select,option,textarea').length)continue;const id=page+'-t'+(++fieldIndex),tag=node.parent.tagName;const label=/^h[1-6]$/.test(tag)?'Heading':tag==='a'||tag==='button'?'Button or link label':tag==='label'?'Field label':text.length>75?'Description':'Text';group.fields.push({id,kind:'text',label,value:node.data.trim()});const span=$('<span></span>').attr('data-cms-text',id).text(node.data);$(node).replaceWith(span);}else if(node.type==='tag'){if(['script','style','svg','pre','select','textarea'].includes(node.tagName)||$(node).is(managed))continue;visit(node);}}}
 visit(node);
 el.find('img').each((_,img)=>{const image=$(img);if(image.closest(managed).length||/assets\/brands\//.test(image.attr('src')||'')||/logo\./.test(image.attr('src')||''))return;const id=page+'-i'+(++fieldIndex);image.attr('data-cms-image',id);group.fields.push({id,kind:'image',label:image.attr('alt')||'Section picture',value:image.attr('src')||''});});
 el.find('a[href]').each((_,a)=>{const anchor=$(a);if(anchor.closest(managed).length||/^(tel:|mailto:|https:\/\/wa.me)/.test(anchor.attr('href')))return;const id=page+'-l'+(++fieldIndex);anchor.attr('data-cms-link',id);group.fields.push({id,kind:'link',label:'Destination: '+clean(anchor.text()).slice(0,50),value:anchor.attr('href')});});
 group.hint=group.fields.length+' editable text, picture and link fields';if(group.fields.length)content.push(group);
 });
 $('script[src="app.js"],script[src="search-index.js"]').remove();
 if(!$('link[href="cms/public.css"]').length)$('head').append('<link rel="stylesheet" href="cms/public.css">');
 $('body').append('<script type="module" src="cms/public.js"></script>');
 fs.writeFileSync(path.join(root,file),$.html());
}
const posts=fs.existsSync(path.join(root,'data/posts.json'))?JSON.parse(fs.readFileSync(path.join(root,'data/posts.json'),'utf8')).posts.map((p,i)=>({id:'post-'+p.slug,name:p.title,title:p.title,slug:p.slug,date:p.date,category:p.category,excerpt:p.excerpt,image:p.cover,imageAlt:p.coverAlt,body:p.body,author:p.author,visible:p.status==='published'})):[];
for(const brand of brands){const existing=home('img').filter((_,el)=>home(el).attr('src')===brand.image).first();brand.alt=existing.attr('alt')||brand.name;}
const data={schemaVersion:1,products,categories,banners,services,blocks,kits,brands,vehicles,content,pages,posts,menu:[{id:'menu-home',name:'Home',target:'Home',visible:true},...categories.map(c=>({id:'menu-'+c.id,name:c.name,target:c.id,visible:true})),{id:'menu-services',name:'Services',target:'Services',visible:true}],serviceCategories:['Fuel Tank','Sticker Lab','Mastet Service','Premium Master Service','Ceramic Coating','Polish','Painting','Graphic Design'],photos:[],settings:{name:'Moto Market',slogan:'Your Bike, Our Solution',phone:'+880 1711-154387',whatsapp:'+8801711154387',email:'motolubebangladesh@gmail.com',address:'R.A. Khan Chowdhury Road, Kushtia 7000',hours:'Contact the workshop for opening hours',logo:'assets/logo.png',favicon:'assets/logo.png',facebook:'https://www.facebook.com/share/1MLq6PjxjY/',map:'https://maps.google.com/?q=R.A.+Khan+Chowdhury+Road+Kushtia+7000'}};
fs.mkdirSync(path.join(root,'cms'),{recursive:true});fs.writeFileSync(path.join(root,'cms/initial-content.json'),JSON.stringify(data,null,2));
console.log(JSON.stringify({products:products.length,banners:banners.length,services:services.length,blocks:blocks.length,contentGroups:content.length,fields:content.reduce((a,c)=>a+c.fields.length,0),vehicles:vehicles.length}));
