import fs from 'node:fs';
import assert from 'node:assert/strict';
import {SUPABASE_URL,PUBLIC_KEY} from '../cms/config.js';
const auth=async(username,password)=>{const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:username+'@staff.motomarket.invalid',password})});const d=await r.json();assert.ok(r.ok,d.msg||'Sign-in failed');return d;};
const call=async(token,action,fields={},expected=200)=>{const r=await fetch(SUPABASE_URL+'/functions/v1/moto-admin',{method:'POST',headers:{apikey:PUBLIC_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,...fields})});const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));return d;};
const publicLive=async()=>{const r=await fetch(SUPABASE_URL+'/rest/v1/moto_live?select=revision,content',{headers:{apikey:PUBLIC_KEY}});assert.equal(r.status,200);return (await r.json())[0];};
const owner=await auth(process.env.MOTO_USERNAME,process.env.MOTO_PASSWORD);const token=owner.access_token;
const baseline=await call(token,'load');let changed=false,staffId;const testName='qa-editor-'+Date.now().toString(36);const testPassword='QA!'+crypto.randomUUID();
try{
 assert.equal(baseline.staff.role,'owner');assert.equal(baseline.draft.content.products.length,38);console.log('PASS owner login and full migrated catalogue');
 for(const table of ['moto_draft','moto_staff','moto_requests','moto_media','moto_revisions','moto_audit']){const r=await fetch(SUPABASE_URL+'/rest/v1/'+table+'?select=*',{headers:{apikey:PUBLIC_KEY}});assert.equal(r.status,401,'anonymous '+table);}
 const forbidden=await fetch(SUPABASE_URL+'/rest/v1/rpc/moto_publish',{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_actor:owner.user.id,p_expected:1,p_public_content:{},p_summary:'forbidden'})});assert.ok(!forbidden.ok);console.log('PASS private tables and publishing RPC inaccessible to visitors');
 await call(token,'staff-create',{username:testName,password:testPassword,name:'Delivery QA account',role:'editor',canPublish:false});let editor=await auth(testName,testPassword);const editorState=await call(editor.access_token,'load');staffId=editorState.staff.user_id;await call(editor.access_token,'staff-list',{},400);await call(editor.access_token,'publish',{version:baseline.draft.version},400);await call(editor.access_token,'staff-update',{userId:owner.user.id},400);console.log('PASS Content Manager cannot access staff credentials or publish without permission');
 const newPassword='Reset!'+crypto.randomUUID();await call(token,'staff-update',{userId:staffId,name:'Delivery QA editor',username:testName,role:'editor',canPublish:false,password:newPassword});editor=await auth(testName,newPassword);assert.equal((await call(editor.access_token,'load')).staff.display_name,'Delivery QA editor');console.log('PASS Administrator edits roles and resets a staff password');
 const imageBytes=fs.readFileSync(new URL('../assets/icons/servicing.png',import.meta.url));const file=owner.user.id+'/'+crypto.randomUUID()+'.png';let response=await fetch(SUPABASE_URL+'/storage/v1/object/moto-media/'+file,{method:'POST',headers:{apikey:PUBLIC_KEY,Authorization:'Bearer '+token,'Content-Type':'image/png'},body:imageBytes});assert.ok(response.ok,await response.text());const uploaded=await call(token,'register-media',{path:file,name:'Delivery QA service icon',width:274,height:208});response=await fetch(SUPABASE_URL+'/storage/v1/object/public/moto-media/'+file);assert.ok(!response.ok);console.log('PASS upload and private draft media access');
 const next=structuredClone(baseline.draft.content);next.products[0].name+=' — delivery check';next.products[0].image='media:'+uploaded.media.id;next.posts||=[];next.posts.push({id:'qa-post',name:'Delivery QA story',slug:'delivery-qa-story',excerpt:'Test introduction',body:'A delivery test story.\n\n## Workshop\n\nText follows the theme.',date:'2026-10-10',author:'Moto Market',image:'assets/icons/servicing.png',visible:true});next.pages.push({id:'qa-page',custom:true,name:'Delivery QA page',title:'Delivery QA page',slug:'delivery-qa-page',description:'Test page',shareImage:'assets/icons/servicing.png',html:'<section class="section"><h1>Delivery QA page</h1></section>',css:'h1{color:#dc1238}',visible:true});
 const saved=await call(editor.access_token,'save',{version:baseline.draft.version,content:next,changes:[{key:'delivery-qa',label:'Delivery verification',detail:'Temporary test'}]});changed=true;
 await call(token,'save',{version:baseline.draft.version,content:next,changes:[]},409);assert.equal((await publicLive()).revision,baseline.live.revision);console.log('PASS real draft save, private changes, stale edit rejection');
 const publication=await call(token,'publish',{version:saved.version});const live=await publicLive();assert.equal(live.revision,publication.revision);assert.ok(live.content.products[0].name.includes('delivery check'));assert.ok(live.content.products[0].image.includes('/moto-public/'));assert.ok(live.content.posts.some(p=>p.id==='qa-post'));assert.ok(live.content.pages.some(p=>p.id==='qa-page'));assert.equal((await fetch(live.content.products[0].image)).status,200);console.log('PASS published product, image, coded page and post served from public content');
 const req=async b=>{const r=await fetch(SUPABASE_URL+'/functions/v1/moto-request',{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify(b)});return {status:r.status,body:await r.json()};};
 const order={key:crypto.randomUUID(),kind:'order',name:'DELIVERY QA — ignore',phone:'01700000000',items:[{id:live.content.products[0].id,qty:1}],expectedTotalMinor:(live.content.products[0].sale||live.content.products[0].price)*100,notes:'Automated delivery verification; not a customer order.'};const attempts=await Promise.all([req(order),req(order)]);assert.equal(attempts[0].status,200,JSON.stringify(attempts[0]));assert.equal(attempts[0].body.receipt,attempts[1].body.receipt);assert.equal((await req({...order,key:crypto.randomUUID(),expectedTotalMinor:1})).status,400);const booking=await req({key:crypto.randomUUID(),kind:'booking',name:'DELIVERY QA — ignore',phone:'01700000000',services:[live.content.services[0].id],date:'',notes:'Automated delivery verification; not a booking.'});assert.equal(booking.status,200,JSON.stringify(booking));const updated=await call(token,'load');for(const r of updated.requests.filter(r=>[attempts[0].body.receipt,booking.body.receipt].includes(r.receipt)))await call(token,'request-update',{id:r.id,version:r.version,status:'cancelled',notes:'Delivery QA completed. No customer action required.'});console.log('PASS order/booking inbox, duplicate retry protection, price tamper rejection and status updates');
 await call(token,'staff-update',{userId:staffId,name:'Delivery QA coordinator',username:testName,role:'service',canPublish:false});const service=await call(editor.access_token,'load');assert.ok(!service.draft);await call(editor.access_token,'save',{version:publication.draftVersion,content:next,changes:[]},400);await call(token,'staff-disable',{userId:staffId,disabled:true});await call(editor.access_token,'load',{},403);console.log('PASS role changes apply to existing sessions and disabled staff lose access');
}finally{
 if(changed){const current=await call(token,'load');await call(token,'restore',{version:current.draft.version,revision:baseline.live.revision});console.log('PASS previous live version restored after delivery checks');}
 if(staffId)await call(token,'staff-disable',{userId:staffId,disabled:true});
}
